### ISSUE TITLE
How to use Google Play Music? 0.8.4

### ISSUE THREAD

**Issue by kevinlekiller** [tomahawk-player/tomahawk#355]
I've enabled the Google Play Music addon and put in my google.com information and enabled the less secure apps option in my account.

I can't find where to access the music.

If I click the black icon in the top right, it says "Connections" but there's nothing displayed there, if I click "Connect All" nothing happens.

In the log file all I see that looks relevant is (removed the username): `Mon Dec 7 2015 - 16:05:13 [8]: Got status message with login info: true "my_username" `

Thanks.

**Comment by kevinlekiller** [comment]
Compiled from master, seems to have resolved most issues I was having.

**Comment by muesli** [comment]
Nice, thanks for the feedback!

**Comment by jessi-jamez** [comment]
Hello, i have the same problem. On my new mac. Have the setting enabled less secure apps option. What can i do? Could you help? Thanks for answers. Kind regards.
