### ISSUE TITLE
Support ALSA and ideally JACK

### ISSUE THREAD

**Issue by wolftune** [tomahawk-player/tomahawk#361]
Either I'm missing something or this design is missing basic ALSA support.

I try to play and hear nothing, and terminal says

```
[0x7f304c000958] oss audio output error: cannot open OSS device /dev/dsp: No such file or directory
[0x7f304c000958] main audio output error: module not functional
[0x7f305401b4a8] main decoder error: failed to create audio output
```

OSS? Who uses OSS now? ALSA is the standard. I'm on KXStudio, an Ubuntu-based system. I have no OSS. This is not a problem for any other program, as ALSA is the standard thing. I really like Tomahawk as an idea but I can't use it if there's no ALSA support.

Ideally, I'd like a setting to have it output through JACK really. But ALSA is functional.

**Comment by muesli** [comment]
Various backends are supported actually. Which phonon-backend-* packages do you currently have installed? I'd suggest installing phonon-backend-vlc and removing all the other phonon-backend-* on your system, since they're unmaintained by now. This will support a range of sound systems, from OSS to ALSA, PulseAudio and others.

**Comment by wolftune** [comment]
@muesli I already had phonon-backend-vlc installed and selected as the default. I don't see why the existence of phonon-backend-gstreamer would be a problem. I removed it anyway, and it made no difference. I still get that same OSS error. Note: I do not have PulseAudio installed (although that shouldn't matter).

**Comment by wolftune** [comment]
Oh, I see an issue! In my settings, it looks like OSS is selected for the specific "music" category…

**Comment by wolftune** [comment]
Aha! Solved it. What a weird setup. It was the "Device Preference" section set weird

**Comment by dschmidt** [comment]
Don't worry! In master we removed phonon and use libvlc directly. This class of errors should be gone now for good.
