### ISSUE TITLE
symbol lookup error on Arch

### ISSUE THREAD

**Issue by GAumala** [tomahawk-player/tomahawk#370]
I installed Tomahawk a while ago from [AUR](https://aur.archlinux.org/packages/tomahawk/) a while ago, and it's been great. Today I tried to open it, and got this error:
```
tomahawk: symbol lookup error: /usr/lib/libtomahawk.so.0.8.4: undefined symbol: _ZN6Lucene12LuceneObject8toStringEv
```
Anyone knows how can I fix this?

**Comment by muesli** [comment]
I assume the lucene++ package has been upgraded and broke the ABI compatibility, but didn't trigger a recompile of the Tomahawk package. In which case, simply re-install Tomahawk from AUR again. Let me know if that helps!

**Comment by GAumala** [comment]
Yes, that was the problem, Lucene was upgraded recently. Thanks for the help
