### ISSUE TITLE
cover album

### ISSUE THREAD

**Issue by gutierri** [tomahawk-player/tomahawk#376]
Currently I see the window and not the album cover:
![cover album](https://cloud.githubusercontent.com/assets/1111356/12071068/dd1f6fc8-b07e-11e5-8e5f-bbc65fd19936.png)

I think it would be good:
![cover album future](https://cloud.githubusercontent.com/assets/1111356/12071069/dd2249f0-b07e-11e5-97a4-85b7dc402c62.png)

**Comment by dschmidt** [comment]
See #337

**Comment by gutierri** [comment]
@dschmidt Oh!...
