### ISSUE TITLE
Mac Nightly opens to blank view and closed "Discover" section

### ISSUE THREAD

**Issue by jherskowitz** [tomahawk-player/tomahawk#383]
See https://www.dropbox.com/s/2apss4fxf513yzi/Screenshot%202016-01-07%2013.33.18.png?dl=0

**Comment by jherskowitz** [comment]
Also missing Charts section entirely.

**Comment by jherskowitz** [comment]
Also only on nightly build - works fine on self-compiled Master.

**Comment by dschmidt** [comment]
Should be fixed with https://github.com/tomahawk-player/tomahawk/commit/9e91ad6549df7e5cda06fa9dde79c55dcd442d34
