### ISSUE TITLE
Weird mouse back/forward button behaviour

### ISSUE THREAD

**Issue by jancoow** [tomahawk-player/tomahawk#387]
The mouse back/forward buttons doesn't behave like the back/forward buttons in the top left corner. It sometimes skip some pages, or going backwards to the first page.

**Comment by jherskowitz** [comment]
On Master?  Which OS?

**Comment by jancoow** [comment]
On master. Arch Linux on 4.3.3-2

**Comment by dschmidt** [comment]
This is weird, I'm not aware we're even handling mouse forward/back buttons explicitly

**Comment by muesli** [comment]
Fixed by https://github.com/tomahawk-player/tomahawk/commit/81eb22614662d3d6230dfd94874e1b4f7c50f2d9
