### ISSUE TITLE
Localhost API "paused" state

### ISSUE THREAD

**Issue by jherskowitz** [tomahawk-player/tomahawk#393]
FYI, apparently http://localhost:60210/api/1.5/playback/currenttrack  always returns “playing” back as “true” even if paused.

**Comment by dschmidt** [comment]
yes, because paused is a "substate" of playing. We shouldn't just change semantics of this value, we could possibly add a separate "paused" value.

**Comment by dschmidt** [comment]
It's already like that. 

Conclusion:
Refer to playing and paused state in combination.
