### ISSUE TITLE
Songs randomly halt during playback

### ISSUE THREAD

**Issue by jcjolley** [tomahawk-player/tomahawk#394]
Disclaimer: This may actually be two separate issues.

Songs will occasionally halt playback mid-song when using the stations feature.  Sometimes Tomahawk skips to the next song, but sometimes it just hangs until I skip to the next track.

I haven't had time to really dig in, but it looks like  soundcloud might be the perp. (The 2 times I've looked at the source of the song, it's been soundcloud.  I know that's hardly conclusive).

**Comment by dschmidt** [comment]
I can confirm that it happens from time to time, and definitely not only Soundcloud. I see it more often with Spotify I think.

**Comment by chrisamaral** [comment]
I only use the google play integration and it happens at least once every day.

It seems to happen more often when I'm at work (lame shared connection) and during the day so, my wild guess is some kind of failure to recover from network instability.

PS: I'm on linux, and thanks a lot for the work on this!

**Comment by dschmidt** [comment]
What VLC version are you on?

**Comment by chrisamaral** [comment]
I don't have vlc installed on this computer.
I'm on tomahawk 0.8.4 though.

**Comment by dschmidt** [comment]
Ah, install phonon-vlc then and try with that. All other phonon backends tend to behave in very bad ways. Tomahawk Master uses libvlc directly and has even less issues than phonon-vlc

**Comment by chrisamaral** [comment]
Hmm, interesting... thanks for the tip!

So, I just switched from _phonon-qt4-gstreamer 4.8.2-4_ to _phonon-qt4-vlc 0.8.2-4_.
I'll try to keep an eye on that and report back.

**Comment by dschmidt** [comment]
Make sure, vlc is really selected as backend or even better just uninstall the gstreamer backend completely if you havebt done so. A buch of people got :trollface:ed by it already

**Comment by muesli** [comment]
Assuming this to be fixed by switching audio backends. Feel free to re-open if this is still happening to you.
