### ISSUE TITLE
Random chunks of the song are played when streaming from ownCloud (Win7)

### ISSUE THREAD

**Issue by Liarra** [tomahawk-player/tomahawk#397]
Windows 7 Enterprise, 64 bit
Tomahawk 0.8.4 downloaded from https://www.tomahawk-player.org/

## How to reproduce 
Works best if the connection is less than perfect.

1. Add an ownCloud Ampache source. 
2. Play a song from this source for 1-2 minutes.
3. Select an earlier time point in the song timeline.

## Expected behaviour:
1. The song is played in a right order; in the case of connection problems, the playback gets paused, then resumes once the next required chunk of the file is received.

2. If the user selects an earlier time point in the timeline, the playback from the selected time point should start immediately.

## Actual behaviour:
1. The song mostly plays in the right order. However, sometimes the random chunks from a previously loaded song part are played instead. 

2. If the user selects an earlier time point in the timeline, this random chunk has to finish playing first before the playback from the selected time point can start.

**Comment by dschmidt** [comment]
I'm trying to reenable windows nightly (hope to have them working again in the next days), would be good if you could test them then. 
Actually, maybe just try the latest nightly even if it's a few months old. It has the new audio engine and a bunch of other changes that might affect this.

**Comment by Liarra** [comment]
Just checked it in the last Nightly for Windows. Overall the situation seems to have become much better.

However, if the connection drops in the middle of playback, I noticed that Tomahawk might start to infinitely play the last loaded chunk in a loop. Instead I would expect it to just stop the playback after the last available chunk.

**Comment by dschmidt** [comment]
Closing the original report.

Can you file another issue for the connection drop issue?
