### ISSUE TITLE
Garbled sound when using airplay on OSX

### ISSUE THREAD

**Issue by simonvetter** [tomahawk-player/tomahawk#398]
On latest nightly (0.8.99, 20160113), I'm getting garbled sound when using airplay speakers (System Preferences -> Sound -> Output then select your airplay sink instead of Internal Speakers).
It's not noise (I can clearly recognize which music is being played), it sounds more like a starving output due to repeated small buffer underruns.

Stable (0.8.4) has the problem too. It's not a wifi issue -- using wired ethernet all the way produces the same output.
It seems to depend on the input format/bitrate: mp3 and flac at any bitrate are affected while m4a < 128kb/s are played back just fine.
I am only using the local collection resolver.

Other applications (Firefox e.g. playing a youtube video, QuickTime playing movies/mp3s) are unaffected. This is on OSX 10.11.2 on a 13 inch, mid 2012 macbook air.

EDIT: seems like tomahawk is using libvlc, might be related to https://trac.videolan.org/vlc/ticket/14042 .

**Comment by simonvetter** [comment]
I was able to reproduce the problem with stock VLC 2.2.1.
Following the advice on https://trac.videolan.org/vlc/ticket/14042#comment:7 , I changed Preferences -> Input/Codecs -> Network Cache to 3000 (from its default of 1000ms), which solved it.

The value was then set in Library/Preferences/org.videolan.vlc/vlcrc:
```
# Network caching (ms) (integer)
network-caching=3000
```
Unfortunately, libvlc doesn't seem to honor that file when embedded in another application.
I'm now trying to find how to pass it that option from within Tomahawk, which would most likely solve the problem.

**Comment by dschmidt** [comment]
Wow, that's an amazing bug report. Cheers. :beers: 

I'll check back with the VLC guys!

**Comment by fkuehne** [comment]
This is absolutely fine and our currently endorsed workaround - just note that you will have the same delay when switching back from AirPlay to internal speakers...

**Comment by dschmidt** [comment]
@fkuehne thanks! I'll see, maybe it's best to add a setting for this then (just like in VLC)

**Comment by simonvetter** [comment]
Which delay are you referring to? I haven't noticed any playing audio (mp3/m4a) files in VLC with a cache value of 3s. Play/pause/stop/next/previous and seek events all play out instantly on both local and airplay speakers.

I did notice a 2-3s sync problem between audio and video, but that shouldn't affect Tomahawk as it isn't meant to play video files.

**Comment by dschmidt** [comment]
Hey @simonvetter,

I just updated vlc on our osx build machine and triggered a new nightly build. 
Can you try with that one again?

Best regards,
Dominik

**Comment by dschmidt** [comment]
@simonvetter ping

**Comment by simonvetter** [comment]
Sorry, I am currently away from home. Will test and report ASAP (~1-2 weeks or so).

**Comment by dschmidt** [comment]
Fwiw, we tested it at muesli's place the other day and it seemed to work just fine! 

I'm closing this now, if it's not fixed, we can reopen it. Let us know how it goes for you!

**Comment by dschmidt** [comment]
Did you try the nightly build or 0.8?

**Comment by theli-ua** [comment]
To whoever is still having this issue, I've just added ability yo specify arguments to VLC inside tomahawk. You can find that in preferences on advanced tab.
So if network caching 3000 fixes that for you - just go there and put
--network-caching=3000

**Comment by theli-ua** [comment]
@supermensa you can try what I pasted above if you still need it

**Comment by supermensa** [comment]
Thanks, using the nightly build fixed it.
