### ISSUE TITLE
Tomahawk 0.942 doesn't find newly added music from Google Music

### ISSUE THREAD

**Issue by 0schr0eder** [tomahawk-player/tomahawk#402]
I added an album to Google Music, can search for and play tracks in Google Music just fine, but Tomahawk doesn't seem to find tracks from that album. It only returns matching tracks from Soundcloud.

I uninstalled, rebooted and reinstalled Tomahawk to see if that would trigger a library refresh but the behavior didn't change. Using a Nexus 5x with the latest Android January fixes applied.

~~It would be great if one could prioritize search results. For example if I rate Google Music higher than other Music services (like Soundcloud) I would like to see search results that show tracks from Google Music before tracks from Soundcloud.~~

I saw that this is an already existing enhancement request

**Comment by dschmidt** [comment]
@mrmaffen @theli-ua when does gmusic update its collection?

**Comment by mrmaffen** [comment]
This should have been posted here https://github.com/tomahawk-player/tomahawk-android instead. But nevertheless this bug should be fixed with 0.951 :)
