### ISSUE TITLE
No updated nightly versions for Windows?

### ISSUE THREAD

**Issue by ojdo** [tomahawk-player/tomahawk#406]
The nightly versions for Tomahawk seem to receive daily updates for both Android and Mac versions. The Windows folder http://download.tomahawk-player.org/nightly/windows/ however looks stale since September 2015 (`tomahawk-latest.exe` is identical to latest file `tomahawk-0.8.99.20150908-git-master-3751205.exe`). Has the location for those changed?

**Comment by jherskowitz** [comment]
No, we are working on setting up a new Windows build server. Shouldn't be too much longer before those start showing up again. cc @dschmidt

**Comment by dschmidt** [comment]
Yup, highest priority on my todo list. Hope to get it working again by tomorrow night.

**Comment by dschmidt** [comment]
Turned out to be a little more time consuming than I thought, anyway: coming soon.

**Comment by dschmidt** [comment]
Almost there, here's a fresh build from our new build server: http://download.tomahawk-player.org/nightly/windows/tomahawk-0.8.99.20160126-git-master-a5968b5.exe

Needs to be married to our CI system still.

**Comment by dschmidt** [comment]
Fixed.

**Comment by ojdo** [comment]
Just a cosmetic issue: file `tomahawk-latest.exe` - which is the one linked from the homepage - is not yet overwritten.

**Comment by dschmidt** [comment]
Right, will try to fix soon

**Comment by dschmidt** [comment]
Fixed too.
