### ISSUE TITLE
The Ubuntu PPA is missing Ubuntu 16.04 (xenial)

### ISSUE THREAD

**Issue by Mikaela** [tomahawk-player/tomahawk#421]
I know that it's not stable release of Ubuntu, but usually all PPAs are available for even development releases and the current version of Tomahawk in Xenial is `0.7.0+dfsg1-0ubuntu9` which is outdated according to your website.

Sorry if this is wrong place to report this, I found this issue tracker by following link in topic of the IRC channel.

**Comment by ellisistfroh** [comment]
see also launchpad bug-reports:
https://bugs.launchpad.net/ubuntu/+source/tomahawk/+bug/1487729 
(title: Tomahawk 0.8.4 or newer [needs upgrade])
bug-status: in progress

**Comment by justin-time** [comment]
Hi, at the moment we are trying to update the outdated tomahawk package in the official ubuntu sources directly. After this (or if the request fails) we are going to update the PPA.

**Comment by justin-time** [comment]
Tomahawk 0.8.4 is directly available in the official ubuntu 16.04 sources!

**Comment by Spagy** [comment]
@Mikaela, Can this be closed if tomahawk is available from official sources?

**Comment by Mikaela** [comment]
I don't see why not.

> Tomahawk 0.8.4 is directly available in the official ubuntu 16.04 sources!

Sorry, I missed this email, I must have scrolled through it without actually reading.
