### ISSUE TITLE
8 second latency before playing from Spotify

### ISSUE THREAD

**Issue by SlimG** [tomahawk-player/tomahawk#422]
I've used Spotify for years, and just tries Tomahawk today.

I notice that Tomahawk does wait a considerable amount of time before playing tracks from Spotify.

Test environment:
  * Freshly installed Ubuntu Gnome 15.10 64-bit
  * Freshly installed Tomahawk 0.7.0+dfsg1-0ubuntu7 64-bit
  * Freshly installed Spotify 1:1.0.19.106.gb8a7150f 64-bit
  * Freshly installed Clementine 1.2.3+dfsg-4 64-bit
  * Both Spotify and Tomahawk are set to play back standard quality, not high quality. Clementine was left on it's default 320 kbps bitrate.

I tried to time a few songs in both players, the latency measured is fromI hit the Enter-key on a song, and until it starts playing.
  * Spotify: ~40 ms
  * Clementine: ~1500 ms
  * Tomahawk: ~8000 ms

**Comment by dschmidt** [comment]
Tomahawk 0.7.0? That's pretty outdated, can you try 0.8? Or even better try to compile master from source? We changed the audio system a lot after 0.8, worth trying that out imho

**Comment by SlimG** [comment]
Using tomahawk 0.8.99+git20151212+r422+4~ubuntu15.10.1 from https://code.launchpad.net/~justin-time/+archive/ubuntu/tomahawk-nightly (The official PPA does not have the main tomahawk package available for ubuntu 15.10) made a lot of difference. It's now staying around 1000 ms.

I'd recommend you do some magick to try and match the native spotify client's 40 ms playback latency. I also get a feeling tomahawk does not cache it's songs like spotify since it takes 1000 ms even the second time I play the same song.

**Comment by dschmidt** [comment]
Yeah, caching is legally complicated. If libspotify doesn't do it automatically, there's not much we can do. As it seems it's kinda fixed. I'll close it for now, speak up if you disagree :)

**Comment by SlimG** [comment]
A 1000 ms is bearable enough for me to try out Tomahawk as a native Spotify replacement. Thank you for your help dschmidt! :)

**Comment by gnumdk** [comment]
Does Tomahawk use libspotify? Isn't that deprecated?

**Comment by dschmidt** [comment]
It does. Someone filed a bug report saying so without any further explanation. Haven't had a chance to look into it myself, can you provide any more info on that? or what application developers are supposed to use instead?

**Comment by jherskowitz** [comment]
https://developer.spotify.com/technologies/libspotify/

> "LibSpotify and CocoaLibSpotify are no longer under active development on any platform and are considered deprecated. If you are building applications for iOS or Android, please use the iOS SDK or Android SDK. We hope to be able to provide you with a new library for other platforms during 2016.
> 
> Until then, you can still download these libraries and provision new keys for your project. However, please be aware that we cannot offer active support or guarantee future functionality on LibSpotify or CocoaLibSpotify."

Our only option for desktop until there is a new one.

**Comment by dschmidt** [comment]
Yeah, fair enough if they don't drop it completely until there's something new
