### ISSUE TITLE
Congratulations

### ISSUE THREAD

**Issue by dfaropennetwork** [tomahawk-player/tomahawk#424]
For once :D i think that is very important send very very thanks for a great work and the best player ever, and open, better than itunes, spotify, nightingale, rhymbox, all of them

I'm very happy with the player, the desing,all the features are perfect.

very thanx and close the ticket :100:

**Comment by dfaropennetwork** [comment]
![image](https://cloud.githubusercontent.com/assets/13537268/12741923/3082cc12-c981-11e5-865d-e488dd9c5c9c.png)

**Comment by dfaropennetwork** [comment]
Beatufil

**Comment by dschmidt** [comment]
Thanks :beers:

**Comment by dschmidt** [comment]
Woops, typo: meant #425
