### ISSUE TITLE
Style: Icons in context menu on track are very close/overlapping some text

### ISSUE THREAD

**Issue by cruatta** [tomahawk-player/tomahawk#431]
First of all, thanks for Tomahawk! Really awesome so far. I think this is just a stylistic issue but the icons that appear in the context menu when you right click on a track are oddly close and sometimes overlapping the text descriptions of the options. This could be fixed by just increasing the distance between the two by a few pixels.

<img width="391" alt="screen shot 2016-02-10 at 7 48 48 pm" src="https://cloud.githubusercontent.com/assets/2013264/12969064/f6f70a66-d02f-11e5-8f86-3ce7119b1ddc.png">

Build info:
Mac OS X 10.11.1 
TOMAHAWK-VERSION: 0.8.4
PLATFORM: OS X
DBID: 9aaa49c9-4c7d-483c-a83e-0d315d6f619c

**Comment by muesli** [comment]
Can you still reproduce that with the latest nightly? http://download.tomahawk-player.org/nightly/mac/Tomahawk-latest.dmg

**Comment by cruatta** [comment]
Nope! Looks good. Will close this out.
