### ISSUE TITLE
File size display column in "Collection" table uses incorrect unit (Mb rather than MB)

### ISSUE THREAD

**Issue by fishies** [tomahawk-player/tomahawk#439]
I have a song on my local disk which has a file size of 9,522,621 bytes, which is approximately 9.5 Megabytes (MB) or 76.2 Megabits (Mb). However, the "Size" column of my Collection claims that the file is only 9.5 Megabits (Mb).

**Comment by mariusmg2** [comment]
What song?

**Comment by muesli** [comment]
Fixed in master.
