### ISSUE TITLE
Ability to re-scan collection

### ISSUE THREAD

**Issue by cmclaughlin** [tomahawk-player/tomahawk#440]
I would like the ability to manually launch a re-scan of a local collection of files.  I move files around very regularly... typically I download new music into a temp directory and listen to it from there for a few days.  Then I import them into [Beets](http://beets.io/) (the Tomahawk+beets plugin is pretty cool!), which moves them into their final resting place.

I see there's an option to rescan at regular intervals and I just enabled that, but it would also be nice to have the option to kick off a manual rescan.  Currently it looks like I have duplicates until the next re-scan runs.

**Comment by cmclaughlin** [comment]
Opps, just found this in the UI.

**Comment by muesli** [comment]
No problem, glad you found it!
