### ISSUE TITLE
Spotify: Metadata API (End of life)

### ISSUE THREAD

**Issue by mborho** [tomahawk-player/tomahawk#445]
Spotify-Plugin stopped working, I think it's related to this:

https://developer.spotify.com/technologies/metadata-api/

Which means, no metadata anymore from Spotify through Libspotify. The WebApi has to be used now.

**Comment by dschmidt** [comment]
It's fixed for now: https://github.com/clementine-player/Clementine/issues/5238#issuecomment-186468402

Closing as there's no upgrade path for now. We can reopen this once it's clear that libspotify will definitely stop working and when there's a migration plan.
