### ISSUE TITLE
Error compiling, ‘qt_metatype_id’ is not a member of ‘QMetaTypeId<Tomahawk::Accounts::ResolverAccount*>’

### ISSUE THREAD

**Issue by jmansell90** [tomahawk-player/tomahawk#446]
I run make from the build directory (after running cmake) and it gets this far:

[ 92%] Building CXX object src/tomahawk/CMakeFiles/tomahawk-bin.dir/dialogs/SettingsDialog.cpp.o
In file included from /usr/include/QtCore/qvariant.h:48:0,
                 from /usr/include/QtCore/qabstractitemmodel.h:45,
                 from /usr/include/QtCore/QModelIndex:1,
                 from /root/git_files/tomahawk/src/tomahawk/dialogs/SettingsDialog.h:26,
                 from /root/git_files/tomahawk/src/tomahawk/dialogs/SettingsDialog.cpp:22:
/usr/include/QtCore/qmetatype.h: In instantiation of ‘static int QMetaTypeId2<T>::qt_metatype_id() [with T = Tomahawk::Accounts::ResolverAccount*]’:
/usr/include/QtCore/qmetatype.h:230:44:   required from ‘int qMetaTypeId(T*) [with T = Tomahawk::Accounts::ResolverAccount*]’
/usr/include/QtCore/qvariant.h:573:55:   required from ‘T qvariant_cast(const QVariant&) [with T = Tomahawk::Accounts::ResolverAccount*]’
/usr/include/QtCore/qvariant.h:333:36:   required from ‘T QVariant::value() const [with T = Tomahawk::Accounts::ResolverAccount*]’
/root/git_files/tomahawk/src/tomahawk/dialogs/SettingsDialog.cpp:415:158:   required from here
/usr/include/QtCore/qmetatype.h:169:80: error: ‘qt_metatype_id’ is not a member of ‘QMetaTypeId<Tomahawk::Accounts::ResolverAccount*>’
     static inline int qt_metatype_id() { return QMetaTypeId<T>::qt_metatype_id(); }
                                                                                ^
make[2]: *** [src/tomahawk/CMakeFiles/tomahawk-bin.dir/dialogs/SettingsDialog.cpp.o] Error 1
make[1]: *** [src/tomahawk/CMakeFiles/tomahawk-bin.dir/all] Error 2
make: *** [all] Error 2

My qt version is 4.8.5, which matches the minimum of 4.7.0.  I'm not 100% sure what information you might need, but I'd appreciate any help getting to the bottom of why this wont compile.  cmake version is 3.0

**Comment by dschmidt** [comment]
Is that trying to compile master?

**Comment by dschmidt** [comment]
@theli-ua the issue you're having too, right?

**Comment by jmansell90** [comment]
Yeah, that's on the master branch.  I switched to stable branch and still can't compile (this one errors out at EchonestGenerator.cpp saying Echonest::DynamicPlaylist' does not name a type) so I'm thinking this may be my environment but everything meets the minimums.

**Comment by theli-ua** [comment]
Yes

**Comment by dschmidt** [comment]
I can try to fix this one specific issue but I really recommend to compile master and to use qt5 for that. Qt4 support is about to be dropped very soon one way or another

**Comment by dschmidt** [comment]
Also ... why are you compiling as root? (no, not related)

**Comment by dschmidt** [comment]
Can you please try this commit? https://github.com/tomahawk-player/tomahawk/commit/a36694727084

It's in the qt4 branch, alternatively just apply the change manually and let me know if I should apply it to master branch

**Comment by jmansell90** [comment]
> I really recommend to compile master and to use qt5 for that. Qt4 support is about to be dropped very soon one way or another

I tried that too, unfortunately qca2 wouldn't play nice with qt5 on my system along with libattica and qtkeyool.  cmake kept yelling at me that they weren't installed after upgrading to qt5... I reinstalled them to no avail.

> Can you please try this commit? a366947

That compiled for me now, looks like that fixed this issue.  I now have an issue where when I try to run tomahawk I get:

tomahawk: error while loading shared libraries: libtomahawk-widgets.so.0.8.99: cannot open shared object file: No such file or directory

I reran cmake with -DCMAKE_SKIP_RPATH=ON after noticing:

-- Installing: /usr/local/lib64/libtomahawk-widgets.so.0.8.99
-- Installing: /usr/local/lib64/libtomahawk-widgets.so
-- Removed runtime path from "/usr/local/lib64/libtomahawk-widgets.so.0.8.99"

but still doesn't run. Let me know if you need me to have this in a separate issue report.

> Also ... why are you compiling as root? (no, not related)

I was compiling as root because I grabbed the wrong terminal window...  Been tweaking this RHEL build out the wazoo to get it to run on my laptop, got into the habit of having a root shell up instead of typing sudo every 10 seconds.  Yeah, I know, I'm asking for trouble...

**Comment by dschmidt** [comment]
Looking into the shared pointer issue

**Comment by dschmidt** [comment]
Dunno really :-\

About the other deps, make sure they are all qt5 versions of the libs you need. qca and qtkeychain compiled with qt4 won't work to build Tomahawk with Qt5
