### ISSUE TITLE
"Sorry, couldn't find any playable tracks"

### ISSUE THREAD

**Issue by HinkMyDinkD00d** [tomahawk-player/tomahawk#449]
Several albums (Mostly video game soundtracks) refuse to play in the "Albums" column of the Collection tab. However, tracks can be played individually in the "Songs" column without issue.
Affected albums' tracks all have the same Album tag and unique Artist / Title tags.
Tracks also have varying bitrates, if it matters.

**Comment by muesli** [comment]
Dupe of #443.

**Comment by HinkMyDinkD00d** [comment]
Ah ok
Thanks for linking to that other issue
Glad to know that it's being resolved in the next release
