### ISSUE TITLE
Can't seek in tracks resolved by Spotify

### ISSUE THREAD

**Issue by mrmaffen** [tomahawk-player/tomahawk#453]
Whenever I try to seek in a spotify-resolved track it's almost impossible to seek to a certain position. The time it takes to resume playback after seeking seems to depend on how far into the track I want to seek. E.g. skipping to 2:00 takes about 60 seconds while skipping to 0:10 only takes a few seconds. After playback has been resumed I am then unable to seek to the start of the track again.

Just on a side-note: Clementine doesn't support seeking in Spotify tracks at all.

Using my own Qt5 build with HEAD@79cd3a7f0 on Linux Mint 17.2

**Comment by muesli** [comment]
This only started happening recently. Maybe a libspotify issue :-/

**Comment by dschmidt** [comment]
Then we should possibly report it even tho it's not supported anymore. At least they fixed the complete brokenness too

**Comment by xhochy** [comment]
Without testing it, I suspect this commit broke it: https://github.com/tomahawk-player/tomahawk/commit/dde7db616a6aa37dd421d0d5e427d3179d6d626e 

If you pass a plain HTTP Url to VLC, it handles seeks by either waiting a tiny amount or starting a new HTTP Request with the range parameter. Tomahawk's NetworkReply / custom IODevice always waits until the data arrives and never starts a new HTTP request (which would speed stuff up in the Spotify case). You only notice this for Spotify as the HTTP request is throttled by them.

Quick fix: Pass localhost HTTP requests directly to VLC and let it handle the seeks.

Longterm fix: Adjust the VLC API to support HTTP headers.

**Comment by muesli** [comment]
@xhochy Which part of that change do you refer to exactly?

**Comment by muesli** [comment]
Fixed by https://github.com/tomahawk-player/tomahawk/commit/bf28f6856e805505f2715a990c99035a551a3285
