### ISSUE TITLE
Tomahawk freezes after playing track resolved by Amazon

### ISSUE THREAD

**Issue by mrmaffen** [tomahawk-player/tomahawk#467]
After a track resolved by Amazon Prime has been played and I then switch to the next track, Tomahawk freezes up and has to be killed and restarted. This issue is 100% reproducable for me.

Tomahawk HEAD@master, Linux Mint 17.1 64-bit, VLC 2.2.1

[Tomahawk.log.txt](https://github.com/tomahawk-player/tomahawk/files/168266/Tomahawk.log.txt)

**Comment by dschmidt** [comment]
Platform? Version? If linux
what vlc version?

If windows: known, needs vlc update

**Comment by mrmaffen** [comment]
Updated my initial description ...

**Comment by theli-ua** [comment]
Happens to me on OSX following following steps:
Start Amazon Prime stream (probably any HLS stream). Wait till it starts playing, pause, seek to some part of the song .. try to unpause .. switch to a different track

**Comment by theli-ua** [comment]
Forgot to mention, above is 100% reproducible for me with master and vlc 2.2.2

**Comment by dschmidt** [comment]
can you both try with vlc3?

**Comment by theli-ua** [comment]
Is there a formula for vlc3 to use with tomahawk?

**Comment by dschmidt** [comment]
Nope :trollface:

**Comment by theli-ua** [comment]
wasn't able to reproduce my hls freezing issue with 3.0.0-x86_64-20160321-0110  but mostly because it wont allow me to pause hls streams

**Comment by theli-ua** [comment]
I can no longer reproduce this nor on my osx setup (with vlc3) nor with current stable 2.x on my linux box
