### ISSUE TITLE
Randomly fail to play a track on OSX

### ISSUE THREAD

**Issue by theli-ua** [tomahawk-player/tomahawk#471]
vlc-log.txt: 

imem error: Invalid get/release function pointers
imem error: Invalid get/release function pointers
core error: open of `imem://' failed
core error: Your input can't be opened
core error: VLC is unable to open the MRL 'imem://'. Check the log for details.
imem error: Invalid get/release function pointers
imem error: Invalid get/release function pointers
core error: open of `imem://' failed
core error: Your input can't be opened
core error: VLC is unable to open the MRL 'imem://'. Check the log for details.
imem error: Invalid get/release function pointers
imem error: Invalid get/release function pointers
core error: open of `imem://' failed
core error: Your input can't be opened
core error: VLC is unable to open the MRL 'imem://'. Check the log for details.
     
 Tomahawk.log

Wed Mar 16 2016 - 12:20:36 [5]: void AudioEngine::performLoadTrack(const Tomahawk::result_ptr, const QString &, QSharedPointer<QIODevice>) "gmusic://track/Teb2wqjbe5ja6cs37zacmdrobuy" 
Wed Mar 16 2016 - 12:20:36 [0]: void AudioEngine::performLoadTrack(const Tomahawk::result_ptr, const QString &, QSharedPointer<QIODevice>) Starting new song: "https://r12---sn-nx57ynll.c.doc-0-0-sj.sj.googleuse
rcontent.com/videoplayback?id=3cb026b59d869308&itag=25&source=skyjam&begin=0&upn=EPfjl_WNXCU&o=01965815759696022910&ratebypass=yes&ip=54.240.196.185&ipbits=0&expire=1458156126&sparams=expire,id,ip,ipbits,itag,m
m,mn,ms,mv,nh,o,pl,ratebypass,source,upn&signature=1C07E5C5A8787FF58F95824CE1EDEAB58240CC22.8149862717A492DDF1256555AA6087D599657EFA&key=cms1&mm=31&mn=sn-nx57ynll&ms=au&mt=1458155855&mv=m&nh=IgpwcjAxLnNlYTA5Kgk
xMjcuMC4wLjE&pl=24" 
Wed Mar 16 2016 - 12:20:36 [1]: void AudioControls::onControlStateChanged() 
Wed Mar 16 2016 - 12:20:36 [8]: bool AudioEngine::canGoNext() 
Wed Mar 16 2016 - 12:20:36 [8]: Enqueueing command to thread: Tomahawk::DatabaseWorker(0x7fb5117215b0) 0 "loadsocialactions" 
Wed Mar 16 2016 - 12:20:36 [9]: virtual void Tomahawk::DatabaseCommand_LoadSocialActions::exec(Tomahawk::DatabaseImpl *)
Wed Mar 16 2016 - 12:20:36 [9]: Got NEW TRACK LOADING signal
Wed Mar 16 2016 - 12:20:36 [1]: void AudioOutput::setCurrentSource(MediaStream *) 
Wed Mar 16 2016 - 12:20:36 [1]: void AudioOutput::setState(AudioOutput::AudioState) 
Wed Mar 16 2016 - 12:20:36 [1]: void AudioEnginePrivate::onStateChanged(AudioOutput::AudioState, AudioOutput::AudioState) 0 4 4 
Wed Mar 16 2016 - 12:20:36 [1]: void AudioOutput::setCurrentSource(MediaStream *) MediaStream::Final Url: "imem://" 
Wed Mar 16 2016 - 12:20:36 [1]: void AudioOutput::play() 4 
Wed Mar 16 2016 - 12:20:36 [1]: void AudioOutput::setState(AudioOutput::AudioState) 
Wed Mar 16 2016 - 12:20:36 [1]: void AudioEnginePrivate::onStateChanged(AudioOutput::AudioState, AudioOutput::AudioState) 4 4 4 
Wed Mar 16 2016 - 12:20:36 [8]: Enqueueing command to rw thread: "logplayback" 
Wed Mar 16 2016 - 12:20:36 [1]: void AudioOutput::onVlcEvent(const libvlc_event_t *) LibVLC error: MediaPlayerEncounteredError. Stopping 
Wed Mar 16 2016 - 12:20:36 [8]: INSERTING INTO OPLOG: 0 "411bf06d-5018-4be5-ae59-48658f9c6fe4" "logplayback" 
Wed Mar 16 2016 - 12:20:36 [1]: void AudioOutput::setState(AudioOutput::AudioState) 
Wed Mar 16 2016 - 12:20:36 [8]: Singleton command, deleting previous oplog commands 
Wed Mar 16 2016 - 12:20:36 [1]: void AudioEnginePrivate::onStateChanged(AudioOutput::AudioState, AudioOutput::AudioState) 4 3 4 
Wed Mar 16 2016 - 12:20:36 [1]: void AudioEnginePrivate::onStateChanged(AudioOutput::AudioState, AudioOutput::AudioState) AudioOutput Error 
Wed Mar 16 2016 - 12:20:36 [0]: "Sorry, there is a problem accessing your audio device or the desired track, current track will be skipped." 
Wed Mar 16 2016 - 12:20:36 [1]: void AudioEngine::stop(AudioEngine::AudioErrorCode) 3 false 
Wed Mar 16 2016 - 12:20:36 [1]: void AudioOutput::stop() 
Wed Mar 16 2016 - 12:20:36 [1]: void AudioOutput::setState(AudioOutput::AudioState) 
Wed Mar 16 2016 - 12:20:36 [1]: void AudioEnginePrivate::onStateChanged(AudioOutput::AudioState, AudioOutput::AudioState) 3 0 3 
Wed Mar 16 2016 - 12:20:36 [5]: void AudioControls::onPlaybackStopped() 
Wed Mar 16 2016 - 12:20:36 [1]: void AudioControls::onControlStateChanged() 
Wed Mar 16 2016 - 12:20:36 [8]: bool AudioEngine::canGoNext() 
Wed Mar 16 2016 - 12:20:36 [8]: Enqueueing command to rw thread: "logplayback" 
```



Starts working again after few tries.

**Comment by muesli** [comment]
Is this happening with latest stable vlc (2.2.2)?

**Comment by theli-ua** [comment]
I'm using homebrew formula tomahawk-player/tomahawkqt5/vlc which uses 2.2.2 domme should know better which one is it using.

After a bit of investigating
Also - there are 2 separate issues:
1) every second/third track just fails to start and skips to next track
This is not the one described here, should I open another task for it?

2) If you play tomahawk on one network device (say, ethernet).... then you connect over different one (say, wifi) tomahawk just stops being able to succeed any network requests (metadata, radio, etc) until tomahawk is restarted... and this is NOT an audioengine bug, non-audio related network queries will fail as well

**Comment by theli-ua** [comment]
ok, so the 2) is obviously qt issue and is supposedly fixed with qt 5.6
this ticket is about the 1) then

**Comment by theli-ua** [comment]
It looks like this happens when vlc continually gets 0 bytes from our imem callbacks.

**Comment by theli-ua** [comment]
scratch that last statement, in the failure mode callbacks are not called at all

**Comment by theli-ua** [comment]
eh, I believe you do pass invalid pointers occasionally

`const char* imemRelease = QString( "imem-release=%1" ).arg( (uintptr_t)&readDoneCallback ).toLatin1().constData();`

in the above line you create temporary QString object, convert it, get pointer to its internal data ..... and then it gets destroyed.

Technically on the next line memory contents at the address imemRelease points to are undefined

Or am I missing something?

**Comment by theli-ua** [comment]
haven't happened to me once since 1a5f073437487864f84ac1bcab3a67bb3c5d5c40 but I'll leave this open for a few days and keep an eye on if this was what causing that indeed

**Comment by theli-ua** [comment]
Closing this as it seem to be resolved by not using dead memory to pass data to vlc. Will reopen if I ever see it again
