### ISSUE TITLE
Spotify tracks will not play in Ubuntu Linux

### ISSUE THREAD

**Issue by MahmoudDolah** [tomahawk-player/tomahawk#474]
![spotifybug](https://cloud.githubusercontent.com/assets/16995169/13862939/c6cee65c-ec6c-11e5-98ee-fe6d76267d70.png)
I have added my Spotify Premium account, but whenever I click on a song with Spotify as the source, it does not play. 
The time that you see there (1:01) is how long I listened to the previous track. 
No sound comes out of my headphones and the bar that shows how long the song will be remains still. 
Youtube and Soundcloud both work fine and the song will play and everything is displayed correctly under the "Alternate Sources" tab. 
Edit: I am using version 0.8.4 and using the xfce desktop environment.

**Comment by dschmidt** [comment]
What Phonon backend do you use? If you're not using it yet, can you try phonon-vlc?

**Comment by muesli** [comment]
@MahmoudDolah Does that mean switching to phonon-vlc resolved the issue?

**Comment by MahmoudDolah** [comment]
No, in fact, in xfce there is no way to change to phonon-vlc. 
In a completely unrelated thing I was doing, I installed kdeconnect on my android smart phone and computer (which is running xubuntu).
It started working after the installation of kdeconnect. I think this occurred because phonon depends on some other kde library, which was included in the installation of kdeconnect (which resulted in ~90 new installations, which is like half of the kde desktop environment lol)

**Comment by muesli** [comment]
You can always uninstall every other phonon-backend but the -vlc one. They're all broken & unmaintained by now.

**Comment by MahmoudDolah** [comment]
I didn't know that, thanks.
