### ISSUE TITLE
Tomahawk on linux systematically fail on search

### ISSUE THREAD

**Issue by renn0xtek9** [tomahawk-player/tomahawk#477]
Got to the collection. Click on search , type whatsoever, the progrramm crash..
As with any gui from modern days, I doubt such an advanced features have even been tested by the "developper" before it has been tagged a "release" version.
Without what it would not have failed so easily....

It is Kubuntu 14.04 Kde 4

**Comment by muesli** [comment]
As with any bug report from modern days, it would help if the user at least specified which version of the program they use.

**Comment by muesli** [comment]
Closed until more info gets provided.
