### ISSUE TITLE
Google play music plugin does not add account.

### ISSUE THREAD

**Issue by ryanbabcock** [tomahawk-player/tomahawk#481]
No matter what I do, google play does not seem to want to add my account. OSX 0.8.4

**Comment by muesli** [comment]
Google changed it's auth mechanism sometime after we released 0.8.4. Sadly to support the new auth, we need to release a new Tomahawk version with better JS plugin support, first. The good news: It's already working on git-master.

**Comment by muesli** [comment]
Supposedly already fixed, @mrmaffen?
