### ISSUE TITLE
Sharing playlists anonymously on Hatchet

### ISSUE THREAD

**Issue by jnylen** [tomahawk-player/tomahawk#485]
Hi,
Would be wonderful if the playlists could be shareable between Tomahawk users via the site Hatchet or something similar.

**Comment by muesli** [comment]
You can link up your Hatchet account with Tomahawk, which should make all your playlists sync to Hatchet already. You can also export playlists as XSPF. We will bring back anonymously sharing playlists on Hatchet in the future.

**Comment by jnylen** [comment]
Hi,
It syncs to hatchet, but not from hatchet.

How can I export my playlists from hatchet to xspf?

**Comment by jnylen** [comment]
Also: It should be possible to sync between users when its changed etc. Look at the Spotify playlists for example.
