### ISSUE TITLE
Latest Master c62ae52 is broken in image fetching / online actions

### ISSUE THREAD

**Issue by SanKro** [tomahawk-player/tomahawk#486]
i dont know if this is related but after installation of KDE framework 5.20, Qt5.6 and rebuild of tomahawk following things dont work anymore

* cover images (it seems that tomahawk cant fetch them from the servers anymore. all album arts, artist arts .. basically ALL images inside the app dont work anymore.)
* Charts and news simply shows white "sites" without content
* Plugins (the plugin configurations is also blank)

```
%applicationName DIAGNOSTICS LOG -Mon Apr 4 14:31:15 2016 

TOMAHAWK-VERSION: 0.8.99.20160404-git-master-c62ae52
PLATFORM: Linux
DBID: 51c6f88b-e83a-4882-9f33-b7a4f0a8d534

NETWORK:
    Listening to:
      192.168.116.203:50210
      [fd82:6903:8934:1:dafc:93ff:fe11:d6a9]:50210
      [2003:5f:7f43:4147:dafc:93ff:fe11:d6a9]:50210


INFOPLUGINS:
      /usr/lib/libtomahawk_infoplugin_musicbrainz.so
      /usr/lib/libtomahawk_infoplugin_newreleases.so
      /usr/lib/libtomahawk_infoplugin_fdonotify.so
      /usr/lib/libtomahawk_infoplugin_discogs.so
      /usr/lib/libtomahawk_infoplugin_charts.so
      /usr/lib/libtomahawk_infoplugin_mpris.so
      /usr/lib/libtomahawk_infoplugin_hypem.so
      /usr/lib/libtomahawk_infoplugin_rovi.so
      /usr/lib/libtomahawk_infoplugin_echonest.so
      /usr/lib/libtomahawk_infoplugin_musixmatch.so
      /usr/lib/libtomahawk_infoplugin_spotify.so


ACCOUNTS:
RESOLVERS:
DatabaseResolver

```

**Comment by muesli** [comment]
Do you see anything related in the log file? Can't reproduce with Qt 5.6 here.

**Comment by SanKro** [comment]
cant find anything in it, no.
[https://paste.kde.org/pnm2bbksk](https://paste.kde.org/pnm2bbksk)

**Comment by SanKro** [comment]
latest git master works again.
idk what it was bit for now this can be closed. thank you (:

**Comment by dschmidt** [comment]
Maybe some network wonkiness
