### ISSUE TITLE
Tomahawk cuts of start/end of tracks

### ISSUE THREAD

**Issue by theli-ua** [tomahawk-player/tomahawk#500]
I am pretty sure this is an upstream (vlc) problem but still, maybe we can have some workaround

**Comment by dschmidt** [comment]
Moar context?

**Comment by theli-ua** [comment]
Happens for me with HLS streams. Eg there is that song "Nine Inch Nails - Came back haunted" it starts with line "ha - ha - haunted" and sound only starts with "haunted" part. Ie first second or so is muted.

NOW
I just tried to reproduce it and failed. I will retest tomorrow with a different soundcard I usually use with tomahawk (and with which this was reproducible)

**Comment by theli-ua** [comment]
OK
So, this happens on all USB soundcards on OSX that I tried. Does NOT happen with built in soundcard.

**Comment by dschmidt** [comment]
Sounds clearly like a VLC bug, again can you try VLC3? 

@fkuehne any insights?

**Comment by fkuehne** [comment]
tbh, we didn't try with USB sound cards in quite a while. Maybe we should :)

**Comment by dschmidt** [comment]
@fkuehne do you have access to one? otherwise going to be in cologne anytime soon? i could donate a very simple one to VLC :joy:

**Comment by theli-ua** [comment]
still an issue with 3.0.0-x86_64-20160321-0110 nightly, though it cuts off smaller portion at the start of the song

**Comment by theli-ua** [comment]
@dschmidt wrt "clearly a VLC issue" 
I just tested same url that is cut off at the start/end in Tomahawk: it works perfectly fine in VLC itself (using the same libvlc tomahawk is compiled against)

**Comment by dschmidt** [comment]
... oh noes.

**Comment by theli-ua** [comment]
just noticed this is a duplicate of #452
