### ISSUE TITLE
Improvement : Let user the choice between Pulseaudio or Alsa Output

### ISSUE THREAD

**Issue by mathojojo** [tomahawk-player/tomahawk#501]
Pulseaudio is a nice sound server, but as a sound server, it down/upsamples every sound played. It's obligatory if you want more than one source (with different sample rates) to be played.

But for audiophiles user who want to enjoy their HD Music (nativ CD quality 16bit 44.1 kHz, or real HD 24bit 96kHz or even 192kHz), the resampling of the music is a shame ! We would at least need the choice.

For now I switched to DeadBeef (it gives me the choice of ALSA).

I'm used to Tomahawk or Amarok design and functionalities, so I would really appreciate to come back to them...

So please !!!!!!! Implement a way to choose ALSA instead of Pulseaudio as output (I now that using ALSA will disable other sound sources, but it's not important !) 

Thank you for your understanding.

mathojojo

**Comment by githubTids** [comment]
uhm... you can just set pulseaudio to those things (of alsa & your hardware supports it)

```
cat ~/.config/pulse/daemon.conf 
# This file is part of PulseAudio.
#
# PulseAudio is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# PulseAudio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with PulseAudio; if not, see <http://www.gnu.org/licenses/>.

## Configuration file for the PulseAudio daemon. See pulse-daemon.conf(5) for
## more information. Default values are commented out.  Use either ; or # for
## commenting.

; daemonize = no
; fail = yes
; allow-module-loading = yes
; allow-exit = yes
; use-pid-file = yes
; system-instance = no
; local-server-type = user
; enable-shm = yes
; shm-size-bytes = 0 # setting this 0 will use the system-default, usually 64 MiB
; lock-memory = no
; cpu-limit = no

; high-priority = yes
; nice-level = -11

; realtime-scheduling = yes
; realtime-priority = 5

; exit-idle-time = 20
; scache-idle-time = 20

; dl-search-path = (depends on architecture)

; load-default-script-file = yes
; default-script-file = /etc/pulse/default.pa

; log-target = auto
; log-level = notice
; log-meta = no
; log-time = no
; log-backtrace = 0

; resample-method = speex-float-1
; enable-remixing = yes
; enable-lfe-remixing = yes
; lfe-crossover-freq = 120

flat-volumes = no
; flat-volumes = yes

; rlimit-fsize = -1
; rlimit-data = -1
; rlimit-stack = -1
; rlimit-core = -1
; rlimit-as = -1
; rlimit-rss = -1
; rlimit-nproc = -1
; rlimit-nofile = 256
; rlimit-memlock = -1
; rlimit-locks = -1
; rlimit-sigpending = -1
; rlimit-msgqueue = -1
; rlimit-nice = 31
; rlimit-rtprio = 9
; rlimit-rttime = 200000

; default-sample-format = s16le
default-sample-format = s24le
; default-sample-rate = 44100
default-sample-rate = 96000
; alternate-sample-rate = 48000
; default-sample-channels = 2
; default-channel-map = front-left,front-right

; default-fragments = 4
; default-fragment-size-msec = 25

; enable-deferred-volume = yes
; deferred-volume-safety-margin-usec = 8000
; deferred-volume-extra-delay-usec = 0

```

**Comment by mathojojo** [comment]
I'm not sure to understand...

The daemon.conf just allow to set a default sample rate (and an alternate one). It's not dynamic. If I set it to s16le 44.1kHz I will be able to play a sound encoded at 16bit 44.1kHz perfectly... but if next song is a 24bit 192kHz, it will be resampled to 16bit 44.1kHz --> this is not good for my sound quality, at least not good for HIFI. (and of course, changing the daemon.conf and restart pulseaudio to make the change active is not an option :) )

That's why we need to be able to avoid pulseaudio if we want.

Do i miss something ?

**Comment by githubTids** [comment]
@mathojojo no you're right with this. but in this case uninstall pulse. or start tomahawk with
pasuspender. 
if tomahawk would switch to alsa it would make the situation even worse
tomahawk -> ALSA -> pulseaudio alsa wrapper -> pulseaudio -> ALSA -> Hardware
because pulse grabs alsa streams. cause on many systems its only possible to play one alsa stream (i have a system like this D:), all other sound source are muted. thats why pulse was made in first place.
right now its like this
tomahawk -> Pulse -> ALSA -> Hardware.

so all in all ... you should ask the pulseaudio guys to implement a dynamic samplerate feature (and more) ... this would also help other players :)

irc://irc.freenode.org/pulseaudio <- on IRC
https://lists.freedesktop.org/mailman/listinfo/pulseaudio-discuss <- mailinglist

**Comment by mathojojo** [comment]
Are you sure about that : 
tomahawk -> ALSA -> pulseaudio alsa wrapper -> pulseaudio -> ALSA -> Hardware

I would simply say : tomahawk -> ALSA -> Hardware

Of course, that would block other sounds, but I don't care about other sounds when I'm listening my music :) At least, we should have the choice. 

DeadBeef do it : [https://lh3.googleusercontent.com/UFIom69KMcCmkvtVtVujXDu3Xo9rBCPQoAE3ODQQqLwkyOLlX6tsYkTxS_opVJwl21McUEMiQZo=w1280-h1024-no](url)

> you should ask the pulseaudio guys to implement a dynamic samplerate feature (and more) ... this would also help other players :)

I did it, of course, but I think that Pulseaudio developers really don't care about improvement of the quality.
This is me trying to ask a smart resampling feature in pulseaudio:
[https://bugs.freedesktop.org/show_bug.cgi?id=57503](url)

**Comment by mathojojo** [comment]
I don't know why my links don't work when clicked. But they are good (just copy/paste them in the address field of the browser)

**Comment by githubTids** [comment]
> Are you sure about that : 
> tomahawk -> ALSA -> pulseaudio alsa wrapper -> pulseaudio -> ALSA -> Hardware

> DeadBeef do it :

https://imgur.com/Wm5ZIAN <- yep deadbeef goes all the way to alsa, the wrapper, pulse, alsa again and finally reaches the HW. choosing a alsa channel directly doesnt work because pulse blocks it (on my hardware)

what about setting your samplerate to the maximum your hardware supports? wouldnt be the best thing but better then a downsampling

**Comment by mathojojo** [comment]
I think something is wrong in your DeadBeef settings. It should not be possible.

[This is my system running Tomahawk (pulseaudio, not the choice), and DeadBeef (streaming directly to the hardware via Alsa drivers). Of course, Tomahawk is not playing in the same time, he can't as the alsa drivers are already busy with DeadBeef. But as soon, as I stop DeadBeef the playback starts](http://imgur.com/9d2WF4Z).

And in all my reads about DeadBeef, I always read that it is used by audiophile users, because it can speak directly to alsa ! An the sound difference is really sensible, largely better via Alsa... So I think Pulseaudio is not resampling anything.

> what about setting your samplerate to the maximum your hardware supports? wouldnt be the best thing but better then a downsampling

Resampling 48 kHz to 96kHz or 192kHz is not so bad, yes, as they are multiple.  It's not good, but it's still correct!
The problem is that the majority of the music is 44.1 kHz (coming from the CD format). 48 / 44.1 = 1.08843537414966.... The result frequencies of the re-sampling will necessarily be approximative.

Really, the better way would be pulseaudio developers to work on my [idea](https://bugs.freedesktop.org/show_bug.cgi?id=57503) :)

**Comment by theli-ua** [comment]
I just added support to specify additional arguments for VLC used within tomahawk.
You can just use that to specify
--aout=alsa,--alsa-audio-device="alsa device"

**Comment by theli-ua** [comment]
closing as you can tune output as far as vlc command line args allow you to

**Comment by mathojojo** [comment]
Hello,

I don't understand what I should do exactly. How do I use VLC within tomahawk ?

I tried
`tomahawk   --aout=alsa,--alsa-audio-device="sysdefault:CARD=Ultra"`

But tomahawk still use pulseaudio.

thank you

**Comment by theli-ua** [comment]
@mathojojo you need to use master for that.
Then if you go to preferences->advanced there is a new settings "Additional VLC arguments" which you can use

**Comment by mathojojo** [comment]
@theli-ua Thank you for your help. Do you know which version of Tomahawk will integrate this feature ? (I'm not so into building the apps myself, i prefer to use the ppa repositories, so I will wait it there :).

Another thing : Most users won't know how to specify the device. Will it be possible for you to add a simple list of detected alsa devices, in a future version ?

Again, Thank you

**Comment by theli-ua** [comment]
@mathojojo it should be in the next release version. If 0.9 will ever come out it'll be there.
It is potentially doable ofc to integrate audio selection feature, but that would be pretty low on the priority list tbh.
