### ISSUE TITLE
Tomahawk Player no longer opens!

### ISSUE THREAD

**Issue by DroWnThePoor** [tomahawk-player/tomahawk#509]
I've been using this for about a month on Elementary OS Freya, and things have been PERFECT!
Today it has stopped working entirely, I cannot get it to even open.
I believe this issue is somehow related to another issue I'm having with ownCloud-Client for desktop Linux.
I know they both rely on qt somehow, in ownCloud I no longer have the icon in the system tray after last 3 updates. Today's ownCloud-Client update coincides directly with the Tomahawk player no longer working.

Here is what I get when running from terminal, I am sorry of this is alot but I'm not sure what is relevant.

Gtk-Message: Failed to load module "pantheon-filechooser-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Translation: Tomahawk: Using system locale: "en_US" 
Translation: Qt: Using default locale, system locale one not found: "en_US" 
TomahawkApp thread: QThread(0x2621290) 
20:28:19 [0]: Starting Tomahawk... 
20:28:19 [1]: Default font: -1 9 "Roboto" 15 
20:28:19 [0]: void TomahawkUtils::setHeadless(bool) headless is false 
20:28:19 [1]: Setting NAM: QNetworkAccessManager(0x286b970) 
20:28:19 [1]: Init AudioEngine 
20:28:19 [1]: void AudioEngine::setVolume(int) 100 
20:28:19 [1]: Tomahawk::Pipeline::Pipeline(QObject*) Using 4 threads 
20:28:19 [1]: Init Database. 
20:28:19 [5]: Using database: "/home/drown/.local/share/Tomahawk/tomahawk.db" 
20:28:19 [0]: Database schema of "/home/drown/.local/share/Tomahawk/tomahawk.db" "QSQLITE" is 31 
20:28:19 [0]: Database ID: "15a46854-04f6-414c-a8a6-3f0db9d62bd7" 
20:28:19 [1]: Opening Lucene directory: "/home/drown/.local/share/Tomahawk/tomahawk.lucene" 
20:28:19 [1]: Tomahawk::Database::Database(const QString&, QObject*) Using 4 database worker threads 
20:28:19 [0]: void Tomahawk::Database::markAsReady() Database is ready now! 
20:28:19 [1]: virtual void Tomahawk::DatabaseWorkerThread::run() DatabaseWorkerThread starting... 
20:28:19 [1]: virtual void Tomahawk::DatabaseWorkerThread::run() DatabaseWorkerThread starting... 
20:28:19 [1]: virtual void Tomahawk::DatabaseWorkerThread::run() DatabaseWorkerThread starting... 
20:28:19 [1]: virtual void Tomahawk::DatabaseWorkerThread::run() DatabaseWorkerThread starting... 
20:28:19 [1]: virtual void Tomahawk::DatabaseWorkerThread::run() DatabaseWorkerThread starting... 
20:28:19 [1]: Tomahawk::DatabaseWorker::DatabaseWorker(Tomahawk::Database*, bool) New db connection with name: "tomahawk_f6ed11bd-b443-4678-a00c-7950189415ec" on thread Tomahawk::DatabaseWorkerThread(0x2aba620) 
20:28:19 [1]: Tomahawk::DatabaseWorker::DatabaseWorker(Tomahawk::Database*, bool) New db connection with name: "tomahawk_32ee16df-ba5b-4b7d-a8eb-2a9f2b66e9b6" on thread Tomahawk::DatabaseWorkerThread(0x2b3a9f0) 
20:28:19 [1]: Tomahawk::DatabaseWorker::DatabaseWorker(Tomahawk::Database*, bool) New db connection with name: "tomahawk_fb5ffdee-1002-46df-bbbe-648f502ee29c" on thread Tomahawk::DatabaseWorkerThread(0x2ac4a00) 
20:28:19 [1]: Tomahawk::DatabaseWorker::DatabaseWorker(Tomahawk::Database*, bool) New db connection with name: "tomahawk_a74bec63-4d92-4256-9ba3-98f31e8c49dc" on thread Tomahawk::DatabaseWorkerThread(0x2b388a0) 
20:28:19 [1]: Tomahawk::DatabaseWorker::DatabaseWorker(Tomahawk::Database*, bool) New db connection with name: "tomahawk_f5adab4d-1709-4daa-9d0a-95ba739659e8" on thread Tomahawk::DatabaseWorkerThread(0x2b3a570) 
20:28:19 [1]: Init Echonest Factory. 
20:28:19 [1]: Init Database Factory. 
20:28:19 [1]: Init InfoSystem. 
20:28:19 [1]: Tomahawk::InfoSystem::InfoSystemCacheThread::InfoSystemCacheThread(QObject*) 
20:28:19 [1]: Tomahawk::InfoSystem::InfoSystemWorkerThread::InfoSystemWorkerThread(QObject*) 
20:28:19 [1]: Tomahawk::InfoSystem::InfoSystemWorker::InfoSystemWorker() 
20:28:19 [1]: void Tomahawk::Pipeline::start() Shunting 0 queries! 
20:28:19 [1]: Tomahawk::InfoSystem::InfoSystemCache::InfoSystemCache(QObject*) 
20:28:19 [1]: Init AccountManager. 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::init(Tomahawk::InfoSystem::InfoSystemCache*) 
20:28:19 [0]: Load plugins of type "infoplugin" 
20:28:19 [1]: Init MainWindow. 
20:28:19 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "infoplugin" plugins: "/usr/bin" 
20:28:19 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "infoplugin" plugins: "/usr/lib/x86_64-linux-gnu" 
20:28:19 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "infoplugin" plugins: "/usr/lib" 
20:28:19 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "infoplugin" plugins: "/usr" 
20:28:19 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const "infoplugin" plugin file paths: QSet("/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_discogs.so", "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_charts.so", "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_echonest.so", "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_mpris.so", "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_newreleases.so", "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_rovi.so", "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_musixmatch.so", "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_hypem.so", "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_fdonotify.so", "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_spotify.so", "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_musicbrainz.so") 
20:28:19 [1]: Tomahawk::InfoSystem::MusixMatchPlugin::MusixMatchPlugin() 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::loadInfoPlugins() Loaded info plugin: "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_discogs.so" 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::addInfoPlugin(Tomahawk::InfoSystem::InfoPluginPtr) Tomahawk::InfoSystem::DiscogsPlugin(0x7f3da0007470) 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::loadInfoPlugins() Loaded info plugin: "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_charts.so" 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::addInfoPlugin(Tomahawk::InfoSystem::InfoPluginPtr) Tomahawk::InfoSystem::ChartsPlugin(0x7f3da0020d50) 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::loadInfoPlugins() Loaded info plugin: "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_echonest.so" 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::addInfoPlugin(Tomahawk::InfoSystem::InfoPluginPtr) Tomahawk::InfoSystem::EchonestPlugin(0x7f3da0020c50) 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::loadInfoPlugins() Loaded info plugin: "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_mpris.so" 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::addInfoPlugin(Tomahawk::InfoSystem::InfoPluginPtr) Tomahawk::InfoSystem::MprisPlugin(0x7f3da0003b50) 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::loadInfoPlugins() Loaded info plugin: "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_newreleases.so" 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::addInfoPlugin(Tomahawk::InfoSystem::InfoPluginPtr) Tomahawk::InfoSystem::NewReleasesPlugin(0x7f3da000a7f0) 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::loadInfoPlugins() Loaded info plugin: "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_rovi.so" 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::addInfoPlugin(Tomahawk::InfoSystem::InfoPluginPtr) Tomahawk::InfoSystem::RoviPlugin(0x7f3da0015990) 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::loadInfoPlugins() Loaded info plugin: "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_musixmatch.so" 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::addInfoPlugin(Tomahawk::InfoSystem::InfoPluginPtr) Tomahawk::InfoSystem::MusixMatchPlugin(0x7f3da0016d10) 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::loadInfoPlugins() Loaded info plugin: "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_hypem.so" 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::addInfoPlugin(Tomahawk::InfoSystem::InfoPluginPtr) Tomahawk::InfoSystem::HypemPlugin(0x7f3da001a460) 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::loadInfoPlugins() Loaded info plugin: "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_fdonotify.so" 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::addInfoPlugin(Tomahawk::InfoSystem::InfoPluginPtr) Tomahawk::InfoSystem::FdoNotifyPlugin(0x7f3da001c8b0) 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::loadInfoPlugins() Loaded info plugin: "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_spotify.so" 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::addInfoPlugin(Tomahawk::InfoSystem::InfoPluginPtr) Tomahawk::InfoSystem::SpotifyPlugin(0x7f3da001fb30) 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::loadInfoPlugins() Loaded info plugin: "/usr/lib/x86_64-linux-gnu/libtomahawk_infoplugin_musicbrainz.so" 
20:28:19 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::addInfoPlugin(Tomahawk::InfoSystem::InfoPluginPtr) Tomahawk::InfoSystem::MusicBrainzPlugin(0x7f3da001efe0) 
20:28:19 [1]: QVariant TomahawkUtils::Cache::getData(const QString&, const QString&) No such key "chart_sources" 
20:28:19 [1]: QVariant TomahawkUtils::Cache::getData(const QString&, const QString&) No such key "nr_sources" 
20:28:19 [1]: void Tomahawk::InfoSystem::HypemPlugin::chartTypes() Got hypem types 
20:28:19 [5]: void AudioControls::onPlaybackStopped() 
20:28:19 [1]: void AudioControls::onControlStateChanged() 
20:28:19 [1]: Creating AccountModel 
20:28:19 [0]: Load plugins of type "viewpage" 
20:28:19 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "viewpage" plugins: "/usr/bin" 
20:28:19 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "viewpage" plugins: "/usr/lib/x86_64-linux-gnu" 
20:28:19 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "viewpage" plugins: "/usr/lib" 
20:28:19 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "viewpage" plugins: "/usr" 
20:28:19 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const "viewpage" plugin file paths: QSet("/usr/lib/x86_64-linux-gnu/libtomahawk_viewpage_whatsnew_0_8.so", "/usr/lib/x86_64-linux-gnu/libtomahawk_viewpage_newreleases.so", "/usr/lib/x86_64-linux-gnu/libtomahawk_viewpage_charts.so", "/usr/lib/x86_64-linux-gnu/libtomahawk_viewpage_dashboard.so") 
20:28:19 [1]: PluginLoader( "viewpage" ): Loaded valid Tomahawk::ViewPagePlugin from "/usr/lib/x86_64-linux-gnu/libtomahawk_viewpage_whatsnew_0_8.so" 
20:28:19 [1]: PluginLoader( "viewpage" ): Loaded valid Tomahawk::ViewPagePlugin from "/usr/lib/x86_64-linux-gnu/libtomahawk_viewpage_newreleases.so" 
20:28:19 [1]: PluginLoader( "viewpage" ): Loaded valid Tomahawk::ViewPagePlugin from "/usr/lib/x86_64-linux-gnu/libtomahawk_viewpage_charts.so" 
20:28:19 [1]: PluginLoader( "viewpage" ): Loaded valid Tomahawk::ViewPagePlugin from "/usr/lib/x86_64-linux-gnu/libtomahawk_viewpage_dashboard.so" 
20:28:19 [0]: void ViewManager::addDynamicPage(Tomahawk::ViewPagePlugin*, const QString&) Trying to add "whatsnew_0_8" 
20:28:19 [0]: void ViewManager::addDynamicPage(Tomahawk::ViewPagePlugin*, const QString&) Trying to add "newreleases" 
20:28:19 [0]: void ViewManager::addDynamicPage(Tomahawk::ViewPagePlugin*, const QString&) Trying to add "charts" 
20:28:19 [0]: void ViewManager::addDynamicPage(Tomahawk::ViewPagePlugin*, const QString&) Trying to add "dashboard" 
20:28:19 [0]: Tomahawk::ViewPage* ViewManager::showDynamicPage(const QString&) pageName: "dashboard" 
20:28:19 [1]: View page shown: "Feed" 
20:28:19 [1]: Got view page activated for item: "Feed" 
20:28:19 [1]: Got view page activated for index: QModelIndex(5,0,0x29284b0,SourcesModel(0x2ccb490) )  
20:28:19 [1]: void AudioControls::onControlStateChanged() 
20:28:19 [1]: void AudioControls::onControlStateChanged() 
20:28:20 [1]: Init Local Collection. 
20:28:20 [1]: Init Pipeline. 
20:28:20 [1]: Adding resolver "DatabaseResolver" 
20:28:20 [0]: Starting HTTPd on "127.0.0.1" 60210 
20:28:20 [0]: Starting HTTPSd on "127.0.0.1" 60211 
20:28:20 [0]: void PlaydarApi::start() true 
20:28:20 [1]: Init Scrobbler. 
20:28:20 [0]: User-Agent: "Tomahawk/0.8.4 (elementary OS Freya)" 
20:28:20 [0]: Load plugins of type "account" 
20:28:20 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "account" plugins: "/usr/bin" 
20:28:20 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "account" plugins: "/usr/lib/x86_64-linux-gnu" 
20:28:20 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "account" plugins: "/usr/lib" 
20:28:20 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "account" plugins: "/usr" 
20:28:20 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const "account" plugin file paths: QSet("/usr/lib/x86_64-linux-gnu/libtomahawk_account_xmpp.so", "/usr/lib/x86_64-linux-gnu/libtomahawk_account_zeroconf.so", "/usr/lib/x86_64-linux-gnu/libtomahawk_account_google.so", "/usr/lib/x86_64-linux-gnu/libtomahawk_account_hatchet.so") 
20:28:20 [1]: void Tomahawk::Accounts::AccountManager::loadPluginFactories() Loaded plugin factory: "/usr/lib/x86_64-linux-gnu/libtomahawk_account_xmpp.so" "xmppaccount" "Jabber (XMPP)" 
20:28:20 [1]: void Tomahawk::Accounts::AccountManager::loadPluginFactories() Loaded plugin factory: "/usr/lib/x86_64-linux-gnu/libtomahawk_account_zeroconf.so" "zeroconfaccount" "Local Network" 
20:28:20 [1]: void Tomahawk::Accounts::AccountManager::loadPluginFactories() Loaded plugin factory: "/usr/lib/x86_64-linux-gnu/libtomahawk_account_google.so" "googleaccount" "Google" 
20:28:20 [1]: void Tomahawk::Accounts::AccountManager::loadPluginFactories() Loaded plugin factory: "/usr/lib/x86_64-linux-gnu/libtomahawk_account_hatchet.so" "hatchetaccount" "Hatchet" 
20:28:20 [1]: Tomahawk::Accounts::CredentialsManager::CredentialsManager(QObject*) 
20:28:20 [0]: Load plugins of type "configstorage" 
20:28:20 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "configstorage" plugins: "/usr/bin" 
20:28:20 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "configstorage" plugins: "/usr/lib/x86_64-linux-gnu" 
20:28:20 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "configstorage" plugins: "/usr/lib" 
20:28:20 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "configstorage" plugins: "/usr" 
20:28:20 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const "configstorage" plugin file paths: QSet("/usr/lib/x86_64-linux-gnu/libtomahawk_configstorage_telepathy.so", "/usr/lib/x86_64-linux-gnu/libtomahawk_configstorage_telepathy_kde.so") 
20:28:20 [1]: Tomahawk::Accounts::TelepathyConfigStorage::TelepathyConfigStorage(QObject*) 
20:28:20 [1]: void Tomahawk::Accounts::TelepathyConfigStorage::loadConfigWidgetPlugins() 
20:28:20 [0]: Load plugins of type "configstorage_telepathy" 
20:28:20 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "configstorage_telepathy" plugins: "/usr/bin" 
20:28:20 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "configstorage_telepathy" plugins: "/usr/lib/x86_64-linux-gnu" 
20:28:20 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "configstorage_telepathy" plugins: "/usr/lib" 
20:28:20 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "configstorage_telepathy" plugins: "/usr" 
20:28:20 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const "configstorage_telepathy" plugin file paths: QSet("/usr/lib/x86_64-linux-gnu/libtomahawk_configstorage_telepathy_kde.so") 
20:28:20 [1]: void Tomahawk::Accounts::CredentialsManager::loadCredentials(const QString&) keys for service "Tomahawk" : ("sipzeroconf_autocreated", "lastfmaccount_48cffbea", "spotifyaccount_c71937d9", "resolveraccount_f67fbbe5") 
tomahawk: symbol lookup error: /usr/lib/x86_64-linux-gnu/libtomahawk.so.0.8.4: undefined symbol: _ZN9QKeychain15ReadPasswordJob6setKeyERK7QString

**Comment by dschmidt** [comment]
Oh yes! This is relevant indeed, almost missed it:

See the last line: tomahawk: symbol lookup error: /usr/lib/x86_64-linux-gnu/libtomahawk.so.0.8.4: undefined symbol: _ZN9QKeychain15ReadPasswordJob6setKeyERK7QString

This means your binary was linked against an incompatible version of qtkeychain. Make sure you have installed the latest versions of qtkeychain and tomahawk that your distribution offers.

So pretty clearly a distribution issue

**Comment by DroWnThePoor** [comment]
Thank you Dominik!

On Wed, May 18, 2016 at 8:00 AM, Dominik Schmidt <notifications@github.com> wrote:

Oh yes! This is relevant indeed, almost missed it:

See the last line: tomahawk: symbol lookup error: /usr/lib/x86_64-linux-gnu/libtomahawk.so.0.8.4: undefined symbol: _ZN9QKeychain15ReadPasswordJob6setKeyERK7QString

This means your binary was linked against an incompatible version of qtkeychain. Make sure you have installed the latest versions of qtkeychain and tomahawk that your distribution offers.

So pretty clearly a distribution issue

**Comment by e-alfred** [comment]
I have the same problem running Kubuntu 14.04. The version of libqtkeychain0 is 0.6.2-1.1.

**Comment by repsorp** [comment]
Ubuntu 16.04
Same problem here
tomahawk: symbol lookup error: /usr/lib/x86_64-linux-gnu/libtomahawk.so.0.8.4: undefined symbol: _ZN9QKeychain15ReadPasswordJob6setKeyERK7QString
