### ISSUE TITLE
Bandcamp support?

### ISSUE THREAD

**Issue by freeasinbear** [tomahawk-player/tomahawk#510]
Weren't there a bandcamp plugin? It's a gold mine for listening indepement artists and many of their tracks aren't on other services.

**Comment by dschmidt** [comment]
Yes,

https://github.com/tomahawk-player/tomahawk-resolvers/tree/master/bandcampmobile
and
https://github.com/tomahawk-player/tomahawk-resolvers/tree/master/bandcamp

**Comment by freeasinbear** [comment]
Thanks! how can I install it? Why can't I see and install it through tomahawk directly?

**Comment by dschmidt** [comment]
You probably want to use the mobile one, the second one needs an API key which we don't have ... unfortunately. 

You can add it from the config dialog via install plugin, just download the whole folder and select the js file

**Comment by freeasinbear** [comment]
Is the bandcampmobile for the android version?

**Comment by dschmidt** [comment]
No, it's just using lower bandwith mp3s and was reverse engineered from the mobile (unofficial) api. correct me if i'm wrong @theli-ua

**Comment by theli-ua** [comment]
This is correct

**Comment by livejamie** [comment]
Hello, I installed the plugin and I see it in the plugin list but I don't see how to set it up?
