### ISSUE TITLE
ctrl+a/cmd+a should work for the filter input

### ISSUE THREAD

**Issue by bensomers** [tomahawk-player/tomahawk#529]
See title - if you've typed some text in to filter, you should be able to use ctrl+a or cmd+a to select it all. You can click the 'x' button to clear it, but if your hands are on the keyboard (which they are, since you're typing), the standard select-all shortcut is a faster & easier way to clear it (and also interacts with copy+paste, etc.).

(I'm using 0.8.4 on Mac).

**Comment by dschmidt** [comment]
Can you test the nightly build?

**Comment by bensomers** [comment]
Just did, works great! Well done on making the nightly build so easily available, too.

**Comment by dschmidt** [comment]
Neat!
