### ISSUE TITLE
Tomahawk faster

### ISSUE THREAD

**Issue by dannymichel** [tomahawk-player/tomahawk#531]
Not much of an issue rather a question of what was done differently:
I remember tomahawk being incredibly slow to browse through my 4TB lossless library. Its about 20x faster now.
Did you migrate languages or something?

**Comment by dschmidt** [comment]
Really hard to tell:
- there might have been a few optimizations in the file scanner (possibly when you add subdirs of a directory that was already watched)
- libraries that we use might have gotten more efficient (especially relevant here taglib) if you're using a nightly build, Qt5 might have positive results too (who knows)

**Comment by dschmidt** [comment]
Closing as it's not really a bug or anything that requires actual action from us

**Comment by muesli** [comment]
Fwiw, no we didn't switch languages or major deps.
