### ISSUE TITLE
Tomahawk 0.8.4 segfault

### ISSUE THREAD

**Issue by SkeLLLa** [tomahawk-player/tomahawk#538]
I'm running tomahawk player on funtoo linux. Emerged version 0.8.4 and when I try to start, it crashes with segfault.
```
[I] media-sound/tomahawk
     Available versions:  (~)0.8.4-r3 **9999 {aqua debug +hatchet kde qt5 telepathy xmpp}
     Installed versions:  0.8.4-r3(04:42:21 PM 07/13/2016)(hatchet qt5 -aqua -debug -kde -telepathy -xmpp)
```

Full strace log available via link: https://gist.github.com/SkeLLLa/59058f59b568e3bad48b25085c6b7c00

GDB output: https://gist.github.com/SkeLLLa/7d57e1f86e0f84fa776d1bb048028035

Is this issue connected with https://github.com/tomahawk-player/tomahawk/commit/09e9a6e960b7cc29018721075d82ba994dc87ab6?

**Comment by theli-ua** [comment]
I would suggest just unmasking 9999 for now

**Comment by SkeLLLa** [comment]
@theli-ua thanks. Already did it and it now launches.
