### ISSUE TITLE
When starting tomahwak i get segmentation fault.

### ISSUE THREAD

**Issue by fourtytwo** [tomahawk-player/tomahawk#539]
Basically what the title says starting is impossible no matter if i installed it via apt-get or i compile it myself. 
On Ubunutu 16.04. 
Starting it wit the userinterface or with console, in both cases it just shuts down again.

**Comment by theli-ua** [comment]
did you compile it yourself? otherwise what version and where did you get it?

**Comment by fourtytwo** [comment]
i get the current git master... however i had to reset linux anyways so now its working but on another linux installation. So it probably isn't really a solution to the problem

**Comment by theli-ua** [comment]
There is no point in keeping this open then as it seems like you no longer have ways to reproduce the problem. Please reopen if you can though
