### ISSUE TITLE
undefined function when trying to add ampache server

### ISSUE THREAD

**Issue by remoteitguy** [tomahawk-player/tomahawk#541]
Wed Jul 27 2016 - 01:02:45 [0]: "/home/jason/.local/share/Tomahawk/atticaresolvers/ampache/contents/code/ampache.js" : "0"
Wed Jul 27 2016 - 01:02:45 [0]: JAVASCRIPT: "/home/jason/.local/share/Tomahawk/atticaresolvers/ampache/contents/code/ampache.js:77" "TypeError: 'undefined' is not a function (evaluating 'Tomahawk.sha256(this.password)')" "undefined"

Version 0.8.4 with Ubuntu 16 4.4.0-31

**Comment by rseek** [comment]
any preogress on this? 
same problem with Version 0.8.4 and Ubuntu  16.04

**Comment by rseek** [comment]
@remoteitguy this helped me:
` sudo apt-get install libjs-cryptojs`

**Comment by remoteitguy** [comment]
Thanks @rseek
