### ISSUE TITLE
MPD Support

### ISSUE THREAD

**Issue by siddharthist** [tomahawk-player/tomahawk#547]
I don't see MPD (or Mopidy) on Tomahawk's homepage as a supported source for music. Is there a reason not to have these? It seems like they would fit right in with the other streaming music sources.

**Comment by theli-ua** [comment]
well, mpd is not a source to stream tracks, its a player. doesn't feel like it fits tbh

**Comment by siddharthist** [comment]
@theli-ua Thanks for highlighting that difference!

**Comment by duncanjohnhowe** [comment]
I think mpd control would be a good feature; it would make tomahawk be a more direct competitor to RoonLabs software. 

So I use a raspberry pi with a iqaudio dac for some very high quality audio. This is controlled by the MoodeAudio distribution; basically a web-server acts as a front-end to mpd. Although the web-server runs on the pi; in principle it doesn't have to. I suspect with a bit of tweaking you could control multiple computers.
http://moodeaudio.org/

This raspberry pi can either be used with headphones; or plugged into my amp.

Imagine you have Tomahawk controlling this; you have a front end that allows you to explore your music; and play it back where you like.

**Comment by dschmidt** [comment]
@duncanjohnhowe you can stream your audio output over the network to the pi plugged into your amp, with pulseaudio e.g.
