### ISSUE TITLE
Issue installing lucenepp with Homebrew

### ISSUE THREAD

**Issue by lsoldano93** [tomahawk-player/tomahawk#550]
I am attempting to follow the instructions [highlighted here](https://github.com/tomahawk-player/tomahawk/wiki/OS-X---Build-Instructions), but I end up receiving the following error message when attempting the command "brew install --HEAD lucenepp --c++11".

> ==> Installing lucenepp from tomahawk-player/tomahawkqt5
> ==> Cloning https://github.com/luceneplusplus/LucenePlusPlus.git
> Updating /Users/Luke/Library/Caches/Homebrew/lucenepp--git
> ==> Checking out branch master
> ==> mkdir build && cd build && cmake -DENABLE_TEST=OFF ["-DCMAKE_C_FLAGS_RELEASE
> Last 15 lines from /Users/Luke/Library/Logs/Homebrew/lucenepp/01.HEAD-6aec070",:
> /tmp/lucenepp-20160901-65093-167vw5g/src/core/include/LuceneInc.h:20:10: fatal error: 'Lucene.h' file not found
> # include "Lucene.h"
> 
> ```
>      ^
> ```
> 
> 1 error generated.
> CMake Error at /tmp/lucenepp-20160901-65093-167vw5g/cmake/cotire.cmake:1622 (message):
>   cotire: error 1 precompiling
>   /tmp/lucenepp-20160901-65093-167vw5g/build/src/core/cotire/lucene++_CXX_prefix.hxx.
> Call Stack (most recent call first):
>   /tmp/lucenepp-20160901-65093-167vw5g/cmake/cotire.cmake:3090 (cotire_precompile_prefix_header)
> 
> make[2]: **\* [src/core/cotire/lucene++_CXX_prefix.hxx.pch] Error 1
> make[2]: **\* Waiting for unfinished jobs....
> make[1]: **\* [src/core/CMakeFiles/lucene++.dir/all] Error 2
> make: **\* [all] Error 2
> 
> READ THIS: https://git.io/brew-troubleshooting
> If reporting this issue please do so at (not Homebrew/brew):
>   https://github.com/tomahawk-player/homebrew-tomahawkqt5/issues

I am running on OSX 10.11.3 and have run 'brew doctor', but have found nothing that would be conflicting with the lucene packages. Am I doing something incorrectly or is this an issue with Lucene/Brew?

**Comment by dschmidt** [comment]
looks like an issue with luceneplusplus. @muesli can you take a look?

**Comment by hugolm84** [comment]
Not an issue anymore
