### ISSUE TITLE
 Tomahawk 0.8.4 qt5 AUR segmentation  fault issue on start

### ISSUE THREAD

**Issue by Jacobtey** [tomahawk-player/tomahawk#561]
jacobtey@jacobtey-laptop ~ % tomahawk
Translation: Tomahawk: Using system locale: "ru"
Translation: Qt: Using default locale, system locale one not found: "ru"
TomahawkApp thread: QThread(0x266b950)
22:42:10 [0]: Starting Tomahawk... 
22:42:10 [1]: Default font: -1 10 "Roboto" 15 
22:42:10 [0]: void TomahawkUtils::setHeadless(bool) headless is false 
22:42:10 [1]: Setting NAM: QNetworkAccessManager(0x27591f0) 
22:42:10 [1]: Init AudioEngine 
22:42:12 [1]: void AudioEngine::setVolume(int) 75 
22:42:12 [1]: Tomahawk::Pipeline::Pipeline(QObject*) Using 4 threads 
22:42:12 [1]: Init Database. 
22:42:12 [5]: Using database: "/home/jacobtey/.local/share/Tomahawk/tomahawk.db" 
22:42:12 [0]: Database schema of "/home/jacobtey/.local/share/Tomahawk/tomahawk.db" "QSQLITE3" is 31 
22:42:12 [0]: Database ID: "334f0e6e-c69b-49ca-8c46-150fedaac927" 
22:42:12 [1]: Opening Lucene directory: "/home/jacobtey/.local/share/Tomahawk/tomahawk.lucene" 
22:42:13 [1]: Tomahawk::Database::Database(const QString&, QObject*) Using 4 database worker threads 
22:42:13 [1]: virtual void Tomahawk::DatabaseWorkerThread::run() DatabaseWorkerThread starting... 
22:42:13 [1]: virtual void Tomahawk::DatabaseWorkerThread::run() DatabaseWorkerThread starting... 
22:42:13 [1]: virtual void Tomahawk::DatabaseWorkerThread::run() DatabaseWorkerThread starting... 
22:42:13 [1]: virtual void Tomahawk::DatabaseWorkerThread::run() DatabaseWorkerThread starting... 
22:42:13 [0]: void Tomahawk::Database::markAsReady() Database is ready now! 
22:42:13 [1]: virtual void Tomahawk::DatabaseWorkerThread::run() DatabaseWorkerThread starting... 
22:42:13 [1]: Tomahawk::DatabaseWorker::DatabaseWorker(Tomahawk::Database*, bool) New db connection with name: "tomahawk_66884796-4c24-4738-a559-03219434ea71" on thread Tomahawk::DatabaseWorkerThread(0x29e26d0) 
22:42:13 [1]: Tomahawk::DatabaseWorker::DatabaseWorker(Tomahawk::Database*, bool) New db connection with name: "tomahawk_ed92c1a8-404b-41b4-a282-36317792be70" on thread Tomahawk::DatabaseWorkerThread(0x29e2a60) 
22:42:13 [1]: Tomahawk::DatabaseWorker::DatabaseWorker(Tomahawk::Database*, bool) New db connection with name: "tomahawk_22d017eb-61df-4b2f-8889-360f40092a8a" on thread Tomahawk::DatabaseWorkerThread(0x29c6060) 
22:42:13 [1]: Tomahawk::DatabaseWorker::DatabaseWorker(Tomahawk::Database*, bool) New db connection with name: "tomahawk_bb6fac8c-4b16-489b-be85-d9481b9a96b7" on thread Tomahawk::DatabaseWorkerThread(0x29c7070) 
22:42:13 [1]: Tomahawk::DatabaseWorker::DatabaseWorker(Tomahawk::Database*, bool) New db connection with name: "tomahawk_5232ea2c-787f-404a-982a-46c01ac49c82" on thread Tomahawk::DatabaseWorkerThread(0x29e2e60) 
22:42:13 [1]: Init Echonest Factory. 
22:42:13 [1]: Init Database Factory. 
22:42:13 [1]: Init InfoSystem. 
22:42:13 [1]: Tomahawk::InfoSystem::InfoSystemCacheThread::InfoSystemCacheThread(QObject*) 
22:42:13 [1]: Tomahawk::InfoSystem::InfoSystemWorkerThread::InfoSystemWorkerThread(QObject*) 
22:42:13 [1]: Tomahawk::InfoSystem::InfoSystemCache::InfoSystemCache(QObject*) 
22:42:13 [1]: Tomahawk::InfoSystem::InfoSystemWorker::InfoSystemWorker() 
22:42:13 [1]: void Tomahawk::Pipeline::start() Shunting 0 queries! 
22:42:13 [1]: void Tomahawk::InfoSystem::InfoSystemWorker::init(Tomahawk::InfoSystem::InfoSystemCache*) 
22:42:13 [0]: Load plugins of type "infoplugin" 
22:42:13 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "infoplugin" plugins: "/usr/bin" 
22:42:13 [1]: Init AccountManager. 
22:42:13 [1]: Init MainWindow. 
22:42:13 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "infoplugin" plugins: "/usr/lib" 
22:42:13 [1]: const QStringList Tomahawk::Utils::PluginLoader::pluginPaths(const QString&) const Checking directory for "infoplugin" plugins: "/usr/lib" 
[1]    1668 segmentation fault (core dumped)  tomahawk

**Comment by Jacobtey** [comment]
https://aur.archlinux.org/packages/tomahawk-qt5/

**Comment by dschmidt** [comment]
It's not the best idea to use 0.8.4 with Qt5 - while technically possible ymmv. Better go for master, the Qt5 support is much much much better than in 0.8.4. And we're certainly not going to backport all the fixes to 0.8.4, so I'm afraid you're on your own with 0.8.4 and Qt5. (yes, we need to release 0.9, I know)
