### ISSUE TITLE
Player doesn't stop playing after closing app

### ISSUE THREAD

**Issue by CADGuy** [tomahawk-player/tomahawk#568]
When I click on the Close button at the top right of the screen to shut down the app, it doesn't stop playing. I have to click on the icon in the system tray to make the app shut down completely.

**Comment by muesli** [comment]
Closing as that's as designed and pretty much every other music player behaves like that.

**Comment by CADGuy** [comment]
Nonsense. I've used more than a few music players, and I've never seen one behave like that.

**Comment by muesli** [comment]
Use Ctrl+Q or Controls Menu -> Quit. Apps minimizing to the tray isn't exactly a new thing.
