### ISSUE TITLE
Fix website SSL certificate warning

### ISSUE THREAD

**Issue by g4z** [tomahawk-player/tomahawk#570]
Hi, your website will not load correctly due to a certificate issue. see attached screenshot.

![insecure connection - mozilla firefox_001](https://cloud.githubusercontent.com/assets/16230360/19677636/8861f922-9a9a-11e6-9f63-2781b820c9fa.png)

**Comment by carlosalvesuy** [comment]
The certificate has expired.
![tomahawk-player org](https://cloud.githubusercontent.com/assets/1368432/19745044/69a7f33a-9ba6-11e6-9323-4ba7ead9a7fc.png)

**Comment by muesli** [comment]
We'll switch over to Let's Encrypt. Hang tight.

**Comment by tibu** [comment]
Any support needed for this?

**Comment by muesli** [comment]
Thanks everyone. Finally fixed this.
