### ISSUE TITLE
Lots of issues, help please!

### ISSUE THREAD

**Issue by ghost** [tomahawk-player/tomahawk#595]
I am coming across quite a few problems, (I have no programming skills whatsoever so maybe this is just ignorance)

Mac OSX 10.12.3
Tomahawk 0.8.4

- no artwork for any albums of flac files

- tomahawk has greyed out specific tracks from an album, even though they are definitely kept in the same location as the tracks on the album that are there
![screen shot 2017-01-28 at 8 36 56 pm](https://cloud.githubusercontent.com/assets/25399341/22395140/8e32ef6a-e599-11e6-80db-677ff13d67f8.png)

- tomahawk has to reload album artwork and tracks everytime I scroll through the albums in my collection (not sure if this is how it's supposed to work)

- tomahawk uninstalls all plugins I have installed every time I start tomahawk

- also there's a long list of plugins that repeats itself
![screen shot 2017-01-28 at 8 38 13 pm](https://cloud.githubusercontent.com/assets/25399341/22395143/b8db232c-e599-11e6-9619-a8fbea75ea97.png)

- not sure if this is a result of my plugins not really working, but I can't drag and drop links of any kind even after reinstalling all plugins

- One specific album will show up in my collection but when I go into the album the tracks are not there even after waiting for plenty of time, but they show up in my latest additions?
![screen shot 2017-01-28 at 8 39 32 pm](https://cloud.githubusercontent.com/assets/25399341/22395150/fb93dda8-e599-11e6-89cf-3900eabd839f.png)
![screen shot 2017-01-28 at 8 39 44 pm](https://cloud.githubusercontent.com/assets/25399341/22395151/fb9b899a-e599-11e6-999a-bbb64e0e78a2.png)
 
Help me please! I'm sorry if I haven't provided the information you need to help, just tell me if I need to add something, or clarify.

**Comment by dschmidt** [comment]
Note: User was deleted

**Comment by muesli** [comment]
Closing as those issues were already reported.
