### ISSUE TITLE
Crackling in the background when playing certain FLAC files

### ISSUE THREAD

**Issue by vigna** [tomahawk-player/tomahawk#621]
I'm hearing clear "digital noise" (crackling in the background) when listening to certain FLAC files on a MacBook Pro 2016 with Mac Os X 10.12.4 (I can provide a FLAC as an example).

However, the same problem appears when using VLC to play those files. 

If I convert the same FLAC file to WAV and play it with VLC, it sounds fine.

So it appears to be something having to do with on-the-fly decoding of FLAC files. I don't know exactly which library or support software Tomahawk is using, so I'm reporting here.

**Comment by vigna** [comment]
I just verified that with Clementine the same file sounds just fine.

**Comment by theli-ua** [comment]
>However, the same problem appears when using VLC to play those files.
>I don't know exactly which library or support software Tomahawk is using, so I'm reporting here.

Well, tomahawk uses VLC to play files, so there is nothing that could be done if they sounds the same in VLC

**Comment by bitmage** [comment]
I'm also hearing noise, and choppy sound on OSX 10.11.6.  MP3 files.  Don't know if it's the same issue.  The files play fine in other audio players.

**Comment by vigna** [comment]
Upgrate to the nightly build of VLC 3.0. It works.

**Comment by vigna** [comment]
I'm sorry, I have to correct myself: VLC 3.0 plays the file perfectly. Tomahawk has still crackling, even using a night build. I'm moving to Clementine.

**Comment by theli-ua** [comment]
I guess if nightly osx builds were using VLC 3.0 it would solve the problem
