### ISSUE TITLE
Use a non version boost library 

### ISSUE THREAD

**Issue by nonamereq** [tomahawk-player/tomahawk#622]
Please use libboost_libraryname.so instead of libboost_libraryname.so.versionnumber.
When boost library is updated as part of another package the version the player uses will be deleted so we have to copy the current boost lib to the be like the deleted library.

**Comment by dschmidt** [comment]
This is correct and pretty standarx behavior and Tomahawk should be updated alongside boost by your distribution or the boost library with the old soversion should not be removed.

**Comment by dschmidt** [comment]
If this makes things clearer: the non version file of shared libs is usually just a symlink to the current versioned lib.
