### ISSUE TITLE
Not releasing disk space when log file is deleted

### ISSUE THREAD

**Issue by TraylorHead** [tomahawk-player/tomahawk#623]
Hi,

I have version 0.8.4 loaded and running on Win10 64bit system and have notice my free space on the drive shrinking. I also do programming, graphic design and more so I did some checking and I could not locate what has been added to take up the room.

I purchased a larger SSD driver as I though the last few application just updates and took more room.  Then I found it that since them I have lost of 10 G of space.

Looking around today and found the log file for Tomahawk was over 6Gb in size.  When I shut down and restarted Tomahawk the log file reset to 0 and started growing, BUT I did not recover my used disk space.

I tried this a few more times with same results.  I have since then disable reporting of crashes but log file continue to build and grow.

I will look for a way to turn off debug log and recover my lost disk space.

Thanks
Jimmy

**Comment by muesli** [comment]
Your operating system & SSD decide when to release the space.
