### ISSUE TITLE
Why is this Tomahawk's website and the ownsers website giving me a slew of unsafe warnings? (chrome).

### ISSUE THREAD

**Issue by tr1s** [tomahawk-player/tomahawk#625]
Is this application safe to use?  Google Chrome is blocking the owners site and tomahawk's site for potential threats.

**Comment by dschmidt** [comment]
Because the cert is out of date. @muesli can you fix?

**Comment by tr1s** [comment]
It's fixed now. Your cert must be as well @dschmidt.
