### ISSUE TITLE
cmake not working, claims missing dependencies even when installed (Debian Sid)

### ISSUE THREAD

**Issue by hamishmaku** [tomahawk-player/tomahawk#627]
as it says in the title, the dependencies list for Debian 9 fails on install complaining packages can't be found, even though I've installed them all and for the record, I also have Qt5, I'm running Plasma...
----------------------------------------------

➜  build sudo cmake ..
-- Build of crashreporter disabled.
-- Building Tomahawk 0.8.4 ***
-- Could not find Qt5, searching for Qt4 instead...
-- Could NOT find Qt4 (missing:  QT_QTWEBKIT_INCLUDE_DIR QT_QTWEBKIT_LIBRARY) (found suitable version "4.8.7", minimum required is "4.7.0")
-- Could NOT find Echonest: Found unsuitable version "", but required is at least "2.2.0" (found ECHONEST_LIBRARIES-NOTFOUND)
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Could NOT find QJSON (missing:  QJSON_LIBRARIES QJSON_INCLUDE_DIR) (Required is at least version "0.8.1")
-- Could NOT find Taglib (missing:  TAGLIB_INCLUDES TAGLIB_LIBRARIES) (Required is at least version "1.8.0")
-- Could NOT find Sparsehash (missing:  SPARSEHASH_INCLUDE_DIR) 
-- Could NOT find GnuTLS (missing:  GNUTLS_LIBRARY GNUTLS_INCLUDE_DIR) 
-- Checking for module 'qca2'
--   No package 'qca2' found
-- Could NOT find QCA2 (missing:  QCA2_LIBRARIES QCA2_INCLUDE_DIR) 
-- Could NOT find LibAttica (missing:  LIBATTICA_LIBRARIES LIBATTICA_INCLUDE_DIR) (Required is at least version "0.4.0")
-- Could NOT find quazip (missing:  QuaZip_LIBRARY) 
-- Could NOT find Jreen (missing:  JREEN_LIBRARIES JREEN_INCLUDE_DIR) (Required is at least version "1.0.5")
-- Could NOT find LibLastFm (missing:  LIBLASTFM_LIBRARIES LIBLASTFM_INCLUDE_DIRS) (Required is at least version "1.0.0")
CMake Warning at CMakeModules/MacroOptionalFindPackage.cmake:32 (find_package):
  By not providing "FindQtKeychain.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "QtKeychain", but CMake did not find one.

  Could not find a package configuration file provided by "QtKeychain"
  (requested version 0.1.0) with any of the following names:

    QtKeychainConfig.cmake
    qtkeychain-config.cmake

  Add the installation prefix of "QtKeychain" to CMAKE_PREFIX_PATH or set
  "QtKeychain_DIR" to a directory containing one of the above files.  If
  "QtKeychain" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:325 (macro_optional_find_package)

CMake Warning at CMakeModules/FindTelepathyQt.cmake:15 (find_package):
  Could not find a package configuration file provided by "TelepathyQt4" with
  any of the following names:

    TelepathyQt4Config.cmake
    telepathyqt4-config.cmake

  Add the installation prefix of "TelepathyQt4" to CMAKE_PREFIX_PATH or set
  "TelepathyQt4_DIR" to a directory containing one of the above files.  If
  "TelepathyQt4" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeModules/MacroOptionalFindPackage.cmake:32 (find_package)
  CMakeLists.txt:331 (macro_optional_find_package)

-- Could NOT find TelepathyQt (missing:  TELEPATHY_QT_INSTALL_DIR) (Required is at least version "0.9.3")
-- KDE4 is installed, will install protocol file
-- Phonon found; ensure that phonon-vlc is at least 0.4

-----------------------------------------------------------------------------
-- The following external packages were located on your system.
-- This installation will have the extra features provided by these packages.
-----------------------------------------------------------------------------
   * X11 - The Xorg libraries
   * Boost - Provides free peer-reviewed portable C++ source libraries
   * Threads - Threading Library
   * Phonon - The Phonon multimedia library

-----------------------------------------------------------------------------
-- The following OPTIONAL packages could NOT be located on your system.
-- Consider installing them to enable more features from this software.
-----------------------------------------------------------------------------
   * Jreen  <http://qutim.org/jreen / https://github.com/euroelessar/jreen>
     Qt XMPP Library
     Jreen is needed for the Jabber SIP plugin.

   * Telepathy-Qt (Telepathy-Qt is needed for sharing Jabber/GTalk accounts with Telepathy.
 or higher)  <FALSE>
     Telepathy-Qt is a Qt high-level binding for Telepathy, a D-Bus framework for unifying real time communication.
   * KDE4  <https://www.kde.org>
     Provides support for configuring Telepathy Accounts from inside Tomahawk

-----------------------------------------------------------------------------
-- The following REQUIRED packages could NOT be located on your system.
-- You must install these packages before continuing.
-----------------------------------------------------------------------------
   * Qt  <http://qt-project.org>
     A cross-platform application and UI framework
     If you see this, although libqt4-devel is installed, check whether the 
     qtwebkit-devel package and whatever contains QtUiTools is installed too
   * Echonest  <http://projects.kde.org/libechonest>
     Qt library for communicating with The Echo Nest
     libechonest 2.2.0 is needed for dynamic playlists and the infosystem
   * Lucene++  <https://github.com/luceneplusplus/LucenePlusPlus/>
     The open-source, C++ search engine
     Lucene++ is used for indexing the collection
   * QJson  <http://qjson.sf.net>
     Qt library that maps JSON data to QVariant objects
     libqjson is used for encoding communication between Tomahawk instances
   * TagLib  <http://developer.kde.org/~wheeler/taglib.html>
     Audio Meta-Data Library
     taglib is needed for reading meta data from audio files
   * Sparsehash  <https://code.google.com/p/sparsehash/>
     An extremely memory-efficient hash_map implementation.
     Sparsehash is needed for reading metadata of mediastreams and fast
    forward/backward seeking in HTTP streams
   * GnuTLS  <http://gnutls.org/>
     GnuTLS is a secure communications library implementing the SSL, TLS and DTLS protocols and technologies around them.
     GnuTLS is needed for serving the Playdar/HTTP API via TLS
   * QCA2  <http://delta.affinix.com/qca/>
     Provides encryption and signing functions necessary for some resolvers and accounts
   * libattica  <http://download.kde.org/stable/attica/>
     Provides support for installation of resolvers from the Tomahawk website
   * QuaZip  <http://quazip.sourceforge.net/>
     Provides support for extracting downloaded resolvers automatically.
   * liblastfm  <https://github.com/lastfm/liblastfm>
     Qt library for the Last.fm webservices
     liblastfm is needed for scrobbling tracks to Last.fm and fetching cover artwork
   * QtKeychain  <https://github.com/frankosterfeld/qtkeychain>
     Provides support for secure credentials storage

-----------------------------------------------------------------------------

CMake Error at CMakeModules/MacroLogFeature.cmake:152 (MESSAGE):
  Exiting: Missing Requirements
Call Stack (most recent call first):
  CMakeLists.txt:410 (macro_display_feature_log)

-- Configuring incomplete, errors occurred!
See also "/home/preview/apps/tomahawk-0.8.4/build/CMakeFiles/CMakeOutput.log".
See also "/home/preview/apps/tomahawk-0.8.4/build/CMakeFiles/CMakeError.log".
 

---------------------------------------------------------

if anyone could help me through this, it'd be much appreciated.

**Comment by dschmidt** [comment]
Can you try with master instead of 0.8.4?

**Comment by hamishmaku** [comment]
@dschmidt thanks for the suggestion! it recognised my dependencies and is building as I type.

it's such a shame this project is abandoned, it's a really innovative idea for modern music management.

I'm kinda lost in terms of what audio player to use, most of the major ones haven't really updated in years.

**Comment by dschmidt** [comment]
Yeah, it's a shame but we all got caught in real life :-(

**Comment by hamishmaku** [comment]
@dschmidt well it built and installed fine, but now when I open it it gives me this error:

tomahawk: error while loading shared libraries: libtomahawk-widgets.so.0.8.99: cannot open shared object file: No such file or directory


I've tried searching, but couldn't find anything related to it, would you be able to offer any help? 

thanks!

**Comment by dschmidt** [comment]
Well, you could potentially play around with CMake RPATH handling: https://cmake.org/Wiki/CMake_RPATH_handling

Personally I just use `LD_LIBRARY_PATH` in my `.profile`.

**Comment by muesli** [comment]
@hamishmaku Just run Tomahawk from the build dir and you should be fine.

**Comment by hamishmaku** [comment]
thanks @dschmidt & @muesli I added a line in /etc/environment.

it's such a neat idea, it'd be great if another dev group could fork + continue development on this app since it's probab one of the more conceptually advanced players out there.

I hope your collective life stuff goes good, thanks for your work on this project!

**Comment by dschmidt** [comment]
Apparently fixed, closing.

**Comment by msuzoagu** [comment]
Hi @dschmidt! I really love the idea behing Tomahawk and attempting to build it on OS X but running into similar issues as @hamishmaku above. 

```
CMake Deprecation Warning at CMakeLists.txt:8 (CMAKE_POLICY):
  The OLD behavior for policy CMP0023 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Deprecation Warning at CMakeLists.txt:12 (CMAKE_POLICY):
  The OLD behavior for policy CMP0020 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Build of crashreporter disabled.
-- Building Tomahawk 0.8.99.20170831-git-master-00f602e ***
CMake Error at CMakeLists.txt:171 (find_package):
  By not providing "FindQt5WebKitWidgets.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5WebKitWidgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5WebKitWidgets"
  with any of the following names:

    Qt5WebKitWidgetsConfig.cmake
    qt5webkitwidgets-config.cmake

  Add the installation prefix of "Qt5WebKitWidgets" to CMAKE_PREFIX_PATH or
  set "Qt5WebKitWidgets_DIR" to a directory containing one of the above
  files.  If "Qt5WebKitWidgets" provides a separate development package or
  SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/Users/msuzo/code/Tomahawk/tomahawk/build/CMakeFiles/CMakeOutput.log".
```  

I have tried setting `export CMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.9.1/` before running the cmake command - [see build instructions for osx](https://github.com/tomahawk-player/tomahawk/wiki/OS-X---Build-Instructions) - but still getting the same error. 

Any hints please? Greatly appreciated.

**Comment by dschmidt** [comment]
No good news here:
https://github.com/Homebrew/legacy-homebrew/pull/50234

You probably need to install qt5.5 or build a newer one from source with webkit enabled ... or so :-\ 
I'm not on mac myself and can't help currently :-(

Porting to QtWebView is unfortunately non-trivial. We have a few synchronous javascript calls in Tomahawk, which we can't easily replace :-\
