### ISSUE TITLE
Tomahawk not starting

### ISSUE THREAD

**Issue by pcktm** [tomahawk-player/tomahawk#628]
Hello, I compiled the tomahawk myself using the tomahawk-qt5 aur package and it's not starting. Here's the log: https://hastebin.com/wobuvacejo.cpp

**Comment by muesli** [comment]
Might be an old, now incomaptible Tomahawk plugin lingering on your system, which it is trying to load now. Did you ever "make install" Tomahawk after building it manually?

**Comment by PuciekTM** [comment]
I built it using Octopi, so no.

**Comment by dschmidt** [comment]
Can you get us a backtrace? The log isn't really helpful sadly..

**Comment by ognarb** [comment]
try to use tomahawk-git instead of tomahawk-qt5

**Comment by pcktm** [comment]
I'm sorry but I'm no longer using linux because of work. Thanks anyway!
