### ISSUE TITLE
Can't create an account for Hatchet 

### ISSUE THREAD

**Issue by HexaC** [tomahawk-player/tomahawk#629]
In the menu I choose the setting icon of Hatchet then I try the create account button and when I choose the Firefox route it don't come up. I tried to copy the link but the site still not coming up.

**Comment by dschmidt** [comment]
Yeah, Hatchet is dead. :-(

As this doesn't help with Tomahawk development I'm closing this. One should probably disable the plugin until someone revives Hatchet.
