### ISSUE TITLE
Unable to login to spotify

### ISSUE THREAD

**Issue by lufinkey** [tomahawk-player/tomahawk#635]
When I try to log in with spotify, I select "okay" on the permissions dialogue, and then it hangs at this screen forever. ![alt text](https://i.imgur.com/vxucAkL.png)

**Comment by jordangidoin** [comment]
Hello,

Same issue Now...

**Comment by dschmidt** [comment]
still the wrong repo. That screenshot shows the android app. This repo is for the desktop app.
