### ISSUE TITLE
Stretched out/Pixelized Text

### ISSUE THREAD

**Issue by pensono** [tomahawk-player/tomahawk#646]
I just downloaded and installed Tomahawk 0.8.4 on Windows 10 Build 15063.909 version 1703 (somewhat out of date), and I see stretched out text in some specific areas. 

![image](https://user-images.githubusercontent.com/9586990/36290414-e57b4c46-1279-11e8-9c3e-1edd85cdfadf.png)

Let me know if you need more help reproducing.

**Comment by dschmidt** [comment]
Heheh.. that looks ... interesting :)

Give the nightlies a spin, they use a newer Qt version which is the library that drives the whole font rendering and other graphics. While I haven't seen this issue, there are still chances it's already fixed.

If not, I'm afraid noone will fix it anytime soon :-(

**Comment by pensono** [comment]
I just tried the nightly, 0.8.99 and the font rendering looks fine. Thanks!
