### ISSUE TITLE
Repository for ubuntu doesn't work

### ISSUE THREAD

**Issue by nachobelmonte** [tomahawk-player/tomahawk#649]
This is what happens when I start to add the ubunut repository in my KdeNeon 

$ sudo add-apt-repository ppa:tomahawk/ppa

 Ubuntu Packages for the Tomahawk social media player.

For Ubuntu 16.04 users: Tomahawk 0.8.4 is in the official ubuntu sources!
 Más información: https://launchpad.net/~tomahawk/+archive/ubuntu/ppa
Pulse [Intro] para continuar o ctrl-c para cancelar

gpg: anillo «/tmp/tmp838clnfy/secring.gpg» creado
gpg: anillo «/tmp/tmp838clnfy/pubring.gpg» creado
gpg: solicitando clave F661FE79 de hkp servidor keyserver.ubuntu.com
gpg: /tmp/tmp838clnfy/trustdb.gpg: se ha creado base de datos de confianza
gpg: clave F661FE79: clave pública "Launchpad PPA for Tomahawk Friends" importada
gpg: Cantidad total procesada: 1
gpg:               importadas: 1  (RSA: 1)
OK

$ sudo apt update

E: The repository «http://ppa.launchpad.net/tomahawk/ppa/ubuntu xenial Release» does not have a Publication file.
N: You can not update from a repository like this in a secure way and therefore it is disabled by default.
N: See the apt-secure (8) man page for details on creating repositories and configuring users.

I dont know if its a problem of my distributions of its a problem of repository.

**Comment by twisp007** [comment]
The project is abandoned. At this point it might be a security risk to use the software.
