### ISSUE TITLE
tomahawk-player.org Certificate Expired

### ISSUE THREAD

**Issue by abraithwaite** [tomahawk-player/tomahawk#650]
FYI.

<img width="479" alt="screen shot 2018-06-26 at 10 08 52 am" src="https://user-images.githubusercontent.com/3791413/41928126-0b4a530c-7929-11e8-9b65-1359df0478b0.png">

**Comment by twisp007** [comment]
Looks like they let this happen. Although I think it's better to just shutdown the site.

**Comment by abraithwaite** [comment]
Goodnight sweet prince.

**Comment by Petrouchka** [comment]
+1

**Comment by hugolm84** [comment]
Fix in #665
