### ISSUE TITLE
Cmake build incorrectly compares versions

### ISSUE THREAD

**Issue by jasoncarr0** [tomahawk-player/tomahawk#655]
In the CMake module for TagLib, a string compare is used on the version instead of the appropriate version comparison. This can be likely fixed by replacing STRLESS with VERSION_LESS  (see https://cmake.org/cmake/help/v3.0/command/if.html)

https://github.com/tomahawk-player/tomahawk/blob/master/CMakeModules/FindTaglib.cmake

**Comment by dschmidt** [comment]
Mind sending a PR?

**Comment by jasoncarr0** [comment]
I'm working on it right now, just checking for other instances.

**Comment by jasoncarr0** [comment]
Oh, turns out this specific instances was actually fixed, but another wasn't, it's just not fixed in teh releases.
