### ISSUE TITLE
Who owns the website?

### ISSUE THREAD

**Issue by fridde** [tomahawk-player/tomahawk#664]
This is obviously a follow up to the [issue](https://github.com/tomahawk-player/tomahawk/issues/647) of this being abandonware, but somehow someone needs to stop the website from spreading malfunctioning binaries and wasting people's time.

Does anyone know who owns the website or domain? Someone must be paying for the domain and/or server.

**Comment by muesli** [comment]
I do. What kind of malfunctioning binaries are you talking about?

**Comment by HackingHyena** [comment]
Right now firefox is throwing up a certificate error on the Tomahawk website and I can't currently access it.

**Comment by hugolm84** [comment]
Fix in #665
