### ISSUE TITLE
Application looks good, but that's about all.........

### ISSUE THREAD

**Issue by ghost** [tomahawk-player/tomahawk#668]
Downloaded and installed the software, and regret doing so.

Allegedly it works with Spotify, does it Hell.  I've been pulling my hair out for at least 6 hours to get it to work with Spotify, and quite frankly am about to smash all my computers up, I'm that annoyed.

It does not recognise ANY of the links from Spotify, and nor does it allow me to import Spotify playlists that I've downloaded to my computer.

The exact path to the directory where it is saved looks nothing like the path indicated in the "Import Playlist" window.  Simply does not exist.

I've tried to manually add the folder where the playlists are stored, but I'm not able to select anything in the folder.

Yep, made my mind up.  Gonna smash-up all my computers (approximately £10,000 worth) then kill myself.

Had it with trying to get software/hardware to work as advertised.

Piece of shit

[Tomahawk.log](https://github.com/tomahawk-player/tomahawk/files/4079858/Tomahawk.log)
L

**Comment by hugolm84** [comment]
Hi

Sorry that you had a bad experience. I'm not sure about the state of the Spotify support, but the way is *should* work is that you drag a spotify URL to the playlist bar and then Tomahawk would create a new playlist with the same content as the one from Spotify. Previously, Tomahawk was able to bi-directionally synch the playlists between Spotify and Tomahawk.

With that said, the player is essentially abandon ware as stated on the main page and I cannot guarantee that things still work with 3rd party integrations. 

If you still think this does not work as advertised, please fill out a bug and perhaps someone can fix it some day. 

Best regards.

**Comment by dschmidt** [comment]
> Yep, made my mind up. Gonna smash-up all my computers (approximately £10,000 worth) then kill myself.

Probably best.
