### ISSUE TITLE
picking up the tomahawk project

### ISSUE THREAD

**Issue by p01arst0rm** [tomahawk-player/tomahawk#671]
seeing as this was completely abandoned, i've picked up this project to work on in my spare time. will be fixing a bunch of stuff and re-hosting binaries soon.

**Comment by hugolm84** [comment]
Hi, great! Please send PR's and I will try to review.

**Comment by dschmidt** [comment]
I can try to help review PRs. Until then this is issue is not really worth anything, closing.
