### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by mrkaban** [tomahawk-player/tomahawk#680]
Thank you very much for the program distributed under a free open license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0/%D0%B2%D0%BE%D1%81%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5/tomahawk-%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0-%D0%BF%D0%BB%D0%B5%D0%B5%D1%80-%D0%B4%D0%BB%D1%8F-%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD-%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D0%BE%D0%B2.html).

Please do not drop the project, this is a very interesting program!

Will the program no longer be updated and new versions will no longer appear?

Will stable versions be published here or elsewhere?

**Comment by dschmidt** [comment]
https://github.com/tomahawk-player/tomahawk#this-project-is-essentially-abandoned
